### ISSUE TITLE
 add images to the top of a gallery

### ISSUE THREAD

**Issue by beatricelucaci** [WPChill/modula-lite#1015]
**Is your feature request related to a problem? Please describe.**
I really wish you would add a feature that allowed adding images to the top of a gallery. Once galleries have a number of photos loaded to them, adding becomes much harder if they are always added to the bottom. Most galleries actually would want the most recent photos added to the top!

**Comment by cristianraiber** [comment]
cc @razvanaldea89 - aici ai facut tu ceva in trecut, era un repo separat

**Comment by razvanaldea89** [comment]
Yup, here it is: https://github.com/WPChill/modula-upload-positioning

**Comment by cristianraiber** [comment]
cc @cristinnaiulia @andrei-l-cristea @beatricelucaci - testam chestia asta si sa vedem daca o putem
merge-ui?

**Comment by beatricelucaci** [comment]
https://github.com/user-attachments/assets/fb213add-2f08-4bec-9b37-3dab526078ea

iar daca am deja galerie facuta, cand apas pe add new imi dispar si imaginile initiale

**Comment by cristinnaiulia** [comment]
+1

**Comment by andrei-l-cristea** [comment]
Mie nu imi dispar imaginile deja adaugate in galerie, dar de fiecare data cand dau "Add new" se face un refresh la pagina.

**Comment by beatricelucaci** [comment]
se poate face ca aceasta functie sa mearga si la Modula Albums, va rog?
