### ISSUE TITLE
Adjustments to the Modula custom grid layout

### ISSUE THREAD

**Issue by andrei-l-cristea** [WPChill/modula-lite#1034]
- [x] Remove the Disable Helper Grid option and always enable this.
- [x] Remove the top left message regarding upload size and drag and drop:

---
<img width="671" alt="Screenshot 2024-09-03 at 11 40 43" src="https://github.com/user-attachments/assets/5c4238dc-5852-40fc-8ea6-c062261c820f">

----

- [x] When uploading files, the progress bar should be moved from the top right corner to the middle of the bottom bar (where the "Disable Helper Grid" was shown). It should only be displayed when the upload is made; this bar should be empty and neutral.
- [x] The Image Upload positioning toggle should be displayed in the top left section instead of the drag-and-drop message.
- [x] The top bar with the upload positioning and add new buttons should be sticky; if you have a large number of images in your gallery and you scroll down, the bar should be visible at all times.
- [x] Verify the links from the Welcome page and make sure that they point to the correct locations
![image](https://github.com/user-attachments/assets/ceaeeec1-5967-4093-ac76-20111fd789d3)
- [x] There is an issue with images not keeping their order when using the BnB gallery type
- [x] The Add new pop-up does not close when clicking outside of the interest area
![image (1)](https://github.com/user-attachments/assets/83420134-4249-40a4-873a-c7c1911bca2b)
- [x] The Add new button should have a visual indicator that it opens a dropdown, similar to here:
https://getbootstrap.com/docs/5.0/components/dropdowns/#split-button
- [x] The Add new button should also display the options available in Pro, but be disabled if you do not have the correct license type and extension enabled
- [x] Add a + sign as an icon to the Add new button to make the button stand out in the layout
- [x] The Bulk Editor button should be displayed even in lite, but when you click it, it should open a upsell message similar to how extensions are handled (for example Image licensing, EXIF...)
- [x] Adjust the contrast for the overlay in BnB gallery layout so that the hidden label is seen better, you can try with rgba(0,0,0,.15)
![image](https://github.com/user-attachments/assets/2474cd95-64ad-4e15-b376-1061947b819c)

**Comment by cristinnaiulia** [comment]
Twitter link from the Welcome page needs to be updated to - https://x.com/wpcontentforge

![Screenshot 2024-09-04 111530](https://github.com/user-attachments/assets/373d1115-07a2-471e-ad11-077c0ffedc9c)
![Screenshot 2024-09-04 111617](https://github.com/user-attachments/assets/808b43ac-7dd5-4943-b344-45b70c3f3459)

**Comment by cristinnaiulia** [comment]
![bnb](https://github.com/user-attachments/assets/07e846a2-ecd3-4fae-a136-93c45b8492c9)
