### ISSUE TITLE
Undefined $screen->base warning while using ACF PRO blocks.

### ISSUE THREAD

**Issue by TeoAlex** [WPChill/modula-lite#1041]
To reproduce:
1. Have Modula and ACF PRO active
2. Create and ACF gutenberg block.
3. Add the block to a page.
4. Check if the block settings work & for console errors.

**Comment by andrei-l-cristea** [comment]
eu am bagat cu gpl kit un acf pro field pe o pagina si nu am vazut nici o eroare in consola
