### ISSUE TITLE
Change the Hover Effects tab

### ISSUE THREAD

**Issue by cristianraiber** [WPChill/modula-lite#114]
Right now, users have no way of actually demo-ing the hover effects that are marked as "pro only"

**Comment by giucu91** [comment]
1. We should rename it in Image Style
2. We should create a list with all hover effects.

**Comment by cristianraiber** [comment]
<img width="1100" alt="image-styles-inlocdehovereffects" src="https://user-images.githubusercontent.com/7841556/103475809-2df12900-4db9-11eb-9d3f-ce036586b92c.png">

---

Instead of showing a dropdown with 53 hover effects, we’ll show them as a “navigator” where you can hover all 53 images quickly and view all the hover effects.

**Comment by giucu91** [comment]
![image](https://user-images.githubusercontent.com/7580330/106767243-52a02100-6643-11eb-9b11-7abf42c869ec.png)

Razvan hai sa incercam sa facem ceva de genu.

**Comment by cristianraiber** [comment]
și poate găsim o soluție sa facem acel scrollbar ceva mai vizibil și stilizat? :)

**Comment by razvanaldea89** [comment]
@cristianraiber were you referring to what was current on the time of the comment or on what @giucu91 posted above ( regarding the scrollbar ) ?

**Comment by cristianraiber** [comment]
@razvanaldea89 - I was talking about the scrollbar for this: https://github.com/WPChill/modula-lite/issues/114#issuecomment-772584001

**Comment by giucu91** [comment]
Urmatoarele efecte nu au preview :

- Catinelle scrie ca ar trebui sa avem social icons.
- Sadie - titlul ar trebui sa fie alb ca sa se vada okish
- Zoe - nu se intelege nimic
- Dexter - ar trebui sa coboram chenarul alb mai jos sa se vada un pic
- Hera pe hover ar trebui sa avem social icons / se vede nasol
- Goliath e ceva dubios
- Kira la fel si aici, cica nu ar avea nimic, dar nu prea are sens.
- Moses - idem
- Duke - pe hover e width mai mare al chenarului

**Comment by razvanaldea89** [comment]
Goliath, kira & moses are going to be deleted/replaced
