### ISSUE TITLE
Hover effects background image

### ISSUE THREAD

**Issue by cristianraiber** [WPChill/modula-lite#121]
- either pick a random image for the users' gallery & allow the user to change it to whatever he likes

**Comment by giucu91** [comment]
If we don't have pictures, we will use our default.

If we have pictures we need to create a slider here in order to our clients to see hover effects on all images.

**Comment by razvanaldea89** [comment]
@giucu91  Maybe it is better if the slider would have 2 images/slide so that the user can have some context. Any opinion on this one?

**Comment by giucu91** [comment]
@razvanaldea89 context ? I don't understand what context

**Comment by razvanaldea89** [comment]
@giucu91  so the user can see how the hover effect works regarding the other non-hovered images

**Comment by giucu91** [comment]
When we scroll the image cut half of arrows.

**Comment by giucu91** [comment]
![image](https://user-images.githubusercontent.com/7580330/77875093-c0c3cc80-7257-11ea-9f72-3f1c5eee331a.png)

Sagetile sunt in afara containerului.
Aliniem textul de jos cu pozele de la slider

**Comment by giucu91** [comment]
@razvanaldea89 wrong informations:
![image](https://user-images.githubusercontent.com/7580330/77879346-e30f1780-7262-11ea-8cc9-ca52d0da7520.png)

we have caption on Pufbro hover effect

**Comment by cristianraiber** [comment]
More details in #114
