### ISSUE TITLE
rubber band effect

### ISSUE THREAD

**Issue by mplusb** [WPChill/modula-lite#133]
I have another recommendation for you concerning Modula - if you don't mind:
the ability to turn off the rubber band effect when using the Custom Grid, it has a mind of its own.

**Comment by mplusb** [comment]
https://photos.google.com/share/AF1QipPmGcEgCVgXgubmv-TdwkR-w02YUDq23VtZpIEtKF8Qefcu73PVd-ssEXwwZHwi0Q/photo/AF1QipMbQjOJInArTeBkUDDqXvON73Muoqy_5lVMj03n?key=X2ZZMXdJeWkxT1NCajlUaXczTXpjekxmOWVkcTV3

**Comment by mplusb** [comment]
I'm having a hard time using the drag and drop. Whenever I drop a video as the start/first one of the gallery, it doesn't move the other gallery to the right, it moved them down and mess up the order of the videos. It's annoying especially if there are a bunch of videos already on the gallery.

**Comment by mplusb** [comment]
+2 
I'm having difficulties dragging my images to organize them. They either won't move to the next "grid" or when they do, a logo will jump to a new row or shuffle the order

**Comment by cristianraiber** [comment]
Look into why packary is affecting the layout when you're doing a drag & drop action

**Comment by razvanaldea89** [comment]
All the sorting system is based on packery, which is based on columns sorting and not rows. For the moment there is nothing that can be done sadly.

**Comment by mplusb** [comment]
+2

**Comment by giucu91** [comment]
I close this, from 2021 no user report this.
