### ISSUE TITLE
doesn't work with cherry framework 3

### ISSUE THREAD

**Issue by mplusb** [WPChill/modula-lite#153]
http://www.cherryframework.com/v3/

**Comment by Florin415** [comment]
If we have modula lite + modula pro installed ( both dev) + the plugins required by the theme installed , the galleries will not be properly displayed : 

Installed plugins : https://prnt.sc/vywebf

Video of a gallery that has filters in it : https://drive.google.com/file/d/1KupQ_PnjIhUdmLvo_ARQk40TTw2nf5tn/view
The images when the gallery has filters in it will receive "display :none" : https://prnt.sc/vyvrok
Gallery that has no filters in it : https://prnt.sc/vyvukq
Errors found in the Cherry options : https://prnt.sc/vyvoew
