### ISSUE TITLE
Add a debug mode 

### ISSUE THREAD

**Issue by cristianraiber** [WPChill/modula-lite#155]
We should look into adding an extra field in Modula's backend that will enable sort of a our proprietary debug mode. This will allow us to easier collect (for support reasons) information from users and hopefully, not need to constantly ask for administrative access - something that most users/customers aren't happy to provide.

**Comment by giucu91** [comment]
Check Health Check WordPress

**Comment by cristianraiber** [comment]
We should hook a few things into Health Check. Like, the required PHP version, imagemagick and whatever else we need (maybe cURL for license checking on the PRO version?)

cc @giucu91

**Comment by cristianraiber** [comment]
- Add an import/export (as JSON) for gallery settings
- Support should direct users to the "Info" tab from Health Check where they can copy to clipboard their system info
- Get Modula to add to the "Info" tab from Health Check various settings from our settings panel/tabs
