### ISSUE TITLE
Integration with Wistia, VooPlayer & Dubb

### ISSUE THREAD

**Issue by cristianraiber** [WPChill/modula-lite#181]
VooPlayer: +12
Dubb: +1
Wistia: +1

This is hugely popular with sumo-lings

**Comment by cristianraiber** [comment]
https://appsumo.com/modula/#q285812 (for reference); will have to re-count all +1's given on AppSumo's deal page AFTER the deal is done.

**Comment by Schokolader** [comment]
+1 VooPlayer

**Comment by kamillabaratom** [comment]
+1 VooPlayer

**Comment by petarsubotic** [comment]
Will gladly make myself available to support your integration efforts with vooPlayer.
FYI, we support both oembed as well as playerjs (http://playerjs.io/), as well as have our own client side and REST API functions for some edge cases. 

- Petar
vooPlayer Product Manager

**Comment by soleskyrolando** [comment]
VooPlayer: +12
Dubb: +1
Publit.io +1
Amazon S3 +1
