### ISSUE TITLE
improve custom responsiveness

### ISSUE THREAD

**Issue by mplusb** [WPChill/modula-lite#215]
if all images are 4:3 in the desktop custom grid. Switching to mobile/tablet they get cropped automatically to a square ratio. They should keep their original form.

**Comment by tarsonis123** [comment]
Well precisely one should be able to keep the aspect ratio for responsive thumbnails. Regardless if it's 4:3 or 3:2 or whatever. If you guys can sort it out I pull the trigger on the pro.

**Comment by cristianraiber** [comment]
@tarsonis123 - this actually seems like a reasonable requirement :) We'll get it sorted out.

cc @giucu91
