### ISSUE TITLE
Gallery not shown when using tabs

### ISSUE THREAD

**Issue by razvanaldea89** [WPChill/modula-lite#224]
When using tabs and gallery is hidden, on tab activation the gallery won't be displayed untill a resize of the window.

**Comment by cristianraiber** [comment]
cc @giucu91 - wasn't this fixed a while back?

**Comment by giucu91** [comment]
@cristianraiber no :(

**Comment by mplusb** [comment]
this is the same issue as: https://github.com/MachoThemes/modula-pro/issues/28
so maybe one of them should be closed?

**Comment by mplusb** [comment]
+9

**Comment by razvanaldea89** [comment]
Seems to be working now. Maybe a fix from other issues fixed this one also?
