### ISSUE TITLE
Image max width problem in some cases

### ISSUE THREAD

**Issue by razvanaldea89** [WPChill/modula-lite#259]
In some cases, the `max-width: 999em` of the image element can cause problems with oversized images in mobile versions. Setting Custom CSS in modula gallery post won't work because of the modula.min.css file that overwrites it, even with `!important`

**Comment by giucu91** [comment]
@razvanaldea89 any link ?

**Comment by razvanaldea89** [comment]
The user changed the way it works so a link won't be useful.
