### ISSUE TITLE
Check compatibility with Oxygen builder

### ISSUE THREAD

**Issue by cristianraiber** [WPChill/modula-lite#284]

**Comment by goninski** [comment]
Modula Gallery not working with Oxygen Builder !!!  Please add compatibilty, otherwise this nice gallery is totaly useless !!

**Comment by cristianraiber** [comment]
@goninski - what have you tried so far? It should work fine with Oxygen + Modula shortcode.

**Comment by goninski** [comment]
@cristianraiber  - hello. I just tested now with clean fresh wp installation. doesn't work. see video https://www.loom.com/share/6dbb7284b651428d922aefdaddf1ee0c. That's a pitty. I bought the modula pro licence ant spent a lot of time to test, but only in gutenberg first, not in oxygen. Hope you can help.

**Comment by goninski** [comment]
@cristianraiber - hi again. I found the reason for this problem. The shortcode element in oxygen needs to have a width of 100% !
