### ISSUE TITLE
Improve publish metabox

### ISSUE THREAD

**Issue by cristianraiber** [WPChill/modula-lite#290]
<img width="280" alt="image" src="https://user-images.githubusercontent.com/7841556/74026206-607a8200-49ae-11ea-9edc-9b8d66f22efc.png">

**Comment by cristianraiber** [comment]
I think we should remove the "safe draft" button here, as well as the "Visibility"and "Publish immediately" links. 

I also think we should a link here that opens up the corresponding tab in the settings metabox that should be improved by the paid extensions. For example, the password protect extension could add a link here and say: "password protected" and have an eye icon to toggle the password display to ON/OFF (to be able to read the password). The speed up estension could display (green) buttons here that show: 

1. lazy load -> enabled 
2. compression -> enabled
3. optimization -> enabled

Same goes for almost every setting that affects the gallery and could be helpful for the user to have a birds eye view.

**Comment by cristianraiber** [comment]
- remove: status from metabox
- remove: published on from metabox
- add: make money with Modula
- add: report a bug

**Comment by giucu91** [comment]
Remove Visibility
![image](https://user-images.githubusercontent.com/7580330/108342039-00cecd80-71e3-11eb-8980-c8ecc3ebd1a9.png)

**Comment by giucu91** [comment]
remove visibility and published on

**Comment by cristinnaiulia** [comment]
Visibility and Published on was removed. Status and save drafts still there. 

![Screenshot 2024-04-25 092958](https://github.com/WPChill/modula-lite/assets/63049546/ff328ae4-9c0f-4658-8fb7-cc2f62494f32)

**Comment by TeoAlex** [comment]
Also merge publish and shortcode metaboxes into one and add filter to show the Status and save draft in case someone wants these back.
