### ISSUE TITLE
Slightly tweaked builder UI

### ISSUE THREAD

**Issue by cristianraiber** [WPChill/modula-lite#293]
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/7841556/74040365-42bc1580-49cc-11ea-86c6-d7986d8802f0.png">

**Comment by cristianraiber** [comment]
I think that having the previewer stretched across the screen would help users get a better view of the space they're working with. The publish metabox is taking 1 column right now for what is an action that you usually need AFTER you've finished playing around with the layout.

I think we could move the publish button on the right hand side of the title field (which is also way too long already)

**Comment by ElectricFeet** [comment]
@cristianraiber 

Agree. And I'd take down those passport photos asap too...

**Comment by cristianraiber** [comment]
@ElectricFeet - yep, thanks for that. I've gone ahead and changed that picture!
