### ISSUE TITLE
Modula Pro feature on ordering?

### ISSUE THREAD

**Issue by ElectricFeet** [WPChill/modula-lite#295]
Modula Gallery Pro allows us to order on:

- Manual
- Date created - newest first
- Date created - oldest first
- Date modified - most recent first
- Date modified - most recent last
- Title alphabetically
- Title reverse
- Random

It would be nice to be able to add a number to each image and use that as the basis for ordering a gallery. 

Why?

Currently, all but the first of the topmost images get shifted down the gallery because they collapse down into columns on mobile. If your most important images are at the top of the gallery, this means that several of them get buried in amongst the less important images, further down. 

If you could assign a number to each image and sort on that, then you could define images to be sorted almost on a "row" basis, by defining the numbers horizontally. This would maintain the "importance" of the topmost images on mobile.

**Comment by cristianraiber** [comment]
@ElectricFeet - this is indeed a nice feature request, but, you're just one person who'd benefit from something as custom as this. Sure, you could argue that once it's public, people might want to play around with it and experiment, but, so far, from what I've seen, people want the easiest & fastest way to create a gallery without having to manually tweak everything. 

Heck, we even have people arguing that our custom grid is too slow for their liking when the whole purpose of it is to give the photographer complete control over how the gallery will end up looking. 

I'm not saying I'm dismissing this idea completely, I'm just saying that it might just be too early for it right now :)
