### ISSUE TITLE
Full Width + Scroll Bar

### ISSUE THREAD

**Issue by giucu91** [WPChill/modula-lite#297]
We have problems with modula on full width pages that don't have scroll bar before gallery initialisation. After initialisation the container of modula will decrease.

**Comment by cristianraiber** [comment]
@giucu91 - potential fix?

**Comment by giucu91** [comment]
I have made something for a client but it's like a hack, and not very optimized.

**Comment by cristianraiber** [comment]
Ties with: #284

**Comment by mplusb** [comment]
+2

**Comment by mplusb** [comment]
+1

**Comment by giucu91** [comment]
+1 https://wordpress.org/support/topic/modula-layout-loads-broken/

**Comment by razvanaldea89** [comment]
Seems to behave like this on smaller screens only. If trying to replicate the issue, make the browser window smaller and do not use browser's responsive view ( if you use browser's responsive view it will work as expected )
