### ISSUE TITLE
 ADA Compliance

### ISSUE THREAD

**Issue by mplusb** [WPChill/modula-lite#299]
https://wordpress.org/support/topic/ada-compliance-13/

**Comment by mplusb** [comment]
+2

**Comment by mplusb** [comment]
errors stating "A link contains no text." for the <a> that opens the lightbox

**Comment by mplusb** [comment]
We are getting an ADA compliancy error. The images (a tag) is not focusable to users using the tab to index through the images. I've tried adding a focus via CSS but it's just not working.

**Comment by cristinnaiulia** [comment]
I ran ADA compliances tests over the site and there were no errors on modula pluglins. 
I used https://accessibe.com/accessscan and Web Accessibility Basic plugin for tests.
 
Scan result: 
[662a1ec07038ee000394443f.pdf](https://github.com/WPChill/modula-lite/files/15107353/662a1ec07038ee000394443f.pdf)
