### ISSUE TITLE
Make Lightbox strings translatable

### ISSUE THREAD

**Issue by razvanaldea89** [WPChill/modula-lite#301]
Offer the possibility to translate strings from lightbox.

**Comment by mplusb** [comment]
+1 translate captions/titles

**Comment by cristianraiber** [comment]
Create a collection of all of our strings and allow users to change them from the plugin's settings panel.

**Comment by giucu91** [comment]
@cristianraiber @razvanaldea89 Since WP have a translation feature I think we should be sure that all our strings can be translated.

**Comment by cristianraiber** [comment]
I agree
