### ISSUE TITLE
When clicking on FB, Twitter, etc share the actual image and not the gallery URL

### ISSUE THREAD

**Issue by cristianraiber** [WPChill/modula-lite#303]

**Comment by andyluak** [comment]
https://stackoverflow.com/questions/12547088/how-do-i-customize-facebooks-sharer-php . Both Facebook and Twitter ( https://stackoverflow.com/questions/18321649/twitter-web-intent-to-post-image/26160761 ) have disabled custom parameters in their sharerers .

**Comment by giucu91** [comment]
I'll close this. #326 have more info.
