### ISSUE TITLE
Improve Gutenblock

### ISSUE THREAD

**Issue by cristianraiber** [WPChill/modula-lite#319]
![image](https://user-images.githubusercontent.com/7841556/75537941-7fee5300-5a20-11ea-8f7b-da9b6c47ae3b.png)

**Comment by cristianraiber** [comment]
Instead of only allowing the user to select an existing gallery, we could enhance it with this type of design. 

Screenshot is taken from this plugin: https://wordpress.org/plugins/visualizer/

**Comment by cristianraiber** [comment]
Ties in with Modula Defaults. We're already working on this.

**Comment by cristianraiber** [comment]
@giucu91 @razvanaldea89 - progress update on this?

**Comment by razvanaldea89** [comment]
Currently this is how the Gallery/Default selection is displayed. User has 2 possibilities, either direct gallery ( a search for gallery input is displayed - selectized ( maybe we should display the first 5 galleries in the dropdown by default ) ) or a preset where you can upload your images.

![image](https://user-images.githubusercontent.com/44024114/131617879-98f823df-ecd0-495f-ae53-b041225ac2f8.png)
