### ISSUE TITLE
Social share information

### ISSUE THREAD

**Issue by razvanaldea89** [WPChill/modula-lite#326]
When sharing an image ( social icon is on image ) it gets the page title. Maybe we should share the image caption/description and not the page title.

**Comment by cristianraiber** [comment]
+1 for image title.

**Comment by cristianraiber** [comment]
And maybe we can also include the caption as the "text" that gets shared with the photo?

**Comment by cristianraiber** [comment]
Duplicate of #303

**Comment by Florin415** [comment]
When use the Share link on twitter from the front it will add the caption in front of the link :https://gyazo.com/88769b91a935ede08925f8b6afd4913e . In lightbox it will not do this :   https://gyazo.com/f23ebab6f7a5aa142bc956c28948d24d
