### ISSUE TITLE
Thoughts for responsive display of Modula settings

### ISSUE THREAD

**Issue by razvanaldea89** [WPChill/modula-lite#336]
Because responsive display needs some "refining" this could be a solution for the issue.

![thoughts for responsive display](https://user-images.githubusercontent.com/44024114/77419832-b629b300-6dd1-11ea-9f7a-4bb75b3fc0d0.jpg)

**Comment by cristianraiber** [comment]
@razvanaldea89 - this can't actually work and/or scale .... :) imagine what happens when the screen resolution gets even smaller than what you've described in your screenshot ...

**Comment by giucu91** [comment]
@razvanaldea89  @cristianraiber Why we have icons on top and not on left like WP ?

**Comment by giucu91** [comment]
![image](https://user-images.githubusercontent.com/7580330/77875742-a38ffd80-7259-11ea-896d-3a8f162460a6.png)

It looks horrible, please rollback and we will take care of this in the next update.

**Comment by cristianraiber** [comment]
We'll explore this further down the road IF any users report issues.
