### ISSUE TITLE
test Modula's dashboard on iPad as well

### ISSUE THREAD

**Issue by mplusb** [WPChill/modula-lite#345]
Seems to be difficult to use the custom grid on an iPad.

Example: I want to change the order of images in the gallery (custom grid), the images are so small and half covered by the triangle of dots that I cannot recognize them.
![Screenshot 2020-03-30 at 17 44 48](https://user-images.githubusercontent.com/26008574/78122572-9d468080-7415-11ea-8bea-0af69b18f49d.jpg)

**Comment by cristianraiber** [comment]
@mplusb - what iPad is this?

**Comment by mplusb** [comment]
@cristianraiber will ask.

deleting images works in custom grid but not in creative gallery. When in the latter mode, when I tried hovering over an image I wanted to delete (in this righthand gallery column) I get the pencil icon but no red button.

**Comment by mplusb** [comment]
iPad pro, latest model running iOS 13.3.1.

**Comment by cristianraiber** [comment]
We'll explore this further down the road.
