### ISSUE TITLE
conflict with ResizeSensor being declared as global

### ISSUE THREAD

**Issue by mplusb** [WPChill/modula-lite#363]
We have a serious conflict with ResizeSensor being declared as global. We already use that library (the latest version) for other stuff. On pages that use Modula, your version conflicts. We cannot dequeue your version because it's bundled into your JS. Could you please consider either: * re-naming your version * removing it from global space somehow * queueing it separately so people with conflicts can dequeue yours We cannot use yours, it doesn't work as well as the latest version, and don't want to include your JS bundle on all pages. As a rather horrible workaround - we've renamed our version of the library. Hope you understand our predicament and will consider taking action

**Comment by mplusb** [comment]
https://secure.helpscout.net/conversation/1138242632/25973?folderId=1289779

**Comment by cristianraiber** [comment]
cc @giucu91 - please investigate

**Comment by Florin415** [comment]
talked with @giucu91 , he will look over this one
