### ISSUE TITLE
incompatibility with Siteground Optimizer Plugin

### ISSUE THREAD

**Issue by mplusb** [WPChill/modula-lite#395]
I have been using Modula Lite, as after trying some other gallery plugins first I found Modula and it did everything i wanted, really well. I really likes how you can drag your images to the tiles squares, and then the post formatted it when published. However it has just stopped working. I am using Modula Lite 2.3.2 and I am sure it happened when I upgraded to the latest version.

The lazy loading button is deactivated, if i activate it on a gallery, then the gallery doesn't appear at all.

I have two speed optimisation plugs in, W3 Cache which i deactivated, and the problem was still there, and then i deactived my Siteground Optimiser plugin and the problem went away, and the galleries are back rendering as they should. So its something to do with the latest version of Modula conflicting with my Siteground Optimizer Plugin

**Comment by razvanaldea89** [comment]
Seems to be an issue when both lazy loading options ( from Modula and SiteGround ) are enabled.

**Comment by cristianraiber** [comment]
> Seems to be an issue when both lazy loading options ( from Modula and SiteGround ) are enabled.

@razvanaldea89 - could we implement a plugin specific check? Check if SG Optimizer is active -> check if their lazyLoad is active -> disable Modula's. 

Same idea should be applied for Avada.

**Comment by razvanaldea89** [comment]
@cristianraiber yes, that is the direction we'll be going
