### ISSUE TITLE
Add gallery id to modula fancybox container class

### ISSUE THREAD

**Issue by razvanaldea89** [WPChill/modula-lite#402]
In some cases, having 2 or more galleries on same page, some of the settings from one gallery will overwrite the others

**Comment by giucu91** [comment]
The lightbox it's destroyed after close. We need to find a solution to be sure that we open the lightbox with proper settings

**Comment by razvanaldea89** [comment]
@giucu91 not only the settings, the config for the lightbox is OK. Talking about some CSS parts that are general for lightbox, not targeted for specific lightboxes. For example, if you create 2 galleries and put them on a page, one with custom lightbox background and one with standard lightbox background, the custom background will be applied to both of them.

**Comment by razvanaldea89** [comment]
Should be tested with about all the settings in the lightbox, including in the PRO version
