### ISSUE TITLE
Custom grid shows image at 100% in the previewer (backend)

### ISSUE THREAD

**Issue by cristianraiber** [WPChill/modula-lite#427]
if you're working with a big number of images or images of big size (in MB), the previewer gets really slow. If we could use a custom image size, something like 1000 x 1000px, I think we could make the previewer a lot faster in rendering the images.

Alternatively, I think we should look into adding lazyLoad into the backend as well and loading images one after the other, as they become available. 

Also, maybe we could look into heavily caching previewers?

**Comment by razvanaldea89** [comment]
@cristianraiber could you double check that it takes the full/big part of the image in the previewer? Tested with a 3 MB image and in the previewer I get the 1024x1024( keeping proportions ) of the image, resulting in a 144 KB size image.

**Comment by cristianraiber** [comment]
@razvanaldea89 - seems to be OK at my end too. 

![image](https://user-images.githubusercontent.com/7841556/101024431-c1e29180-357c-11eb-9210-8c8dc1f777bb.png)

**Comment by razvanaldea89** [comment]
Going to close this
