### ISSUE TITLE
Modula + SPAI

### ISSUE THREAD

**Issue by giucu91** [WPChill/modula-lite#434]
**Describe the bug**
Modula COlumns + SPAI it's not working correctly

**To Reproduce**
1. Create a gallery
2. Select grid type columns
3. select custom image size
4. the columns now have a gap between images

**Expected behavior**
We should add a height auto to images.

**Screenshots**
Before height auto : 
![image](https://user-images.githubusercontent.com/7580330/91430158-8b9fc280-e867-11ea-9833-c8b9fc779b28.png)

After:
![image](https://user-images.githubusercontent.com/7580330/91430499-a7a36400-e867-11ea-94c6-ceb20ed898a5.png)

* Which addons do you have installed: 
- [ ] Modula PRO
- [ ] Albums
- [ ] Slider
- [ ] Lightbox Slideshow
- [ ] Password Protect
- [ ] Watermark
- [ ] Deeplink
- [ ] Right-Click Protection
- [ ] Advanced Shortcode
- [ ] SpeedUp
- [ ] Video

* Which browser is affected (or browsers): 
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other 

* Which device is affected (or devices): 
- [ ] Desktop
- [ ] Tablet
- [ ] Mobile
- [ ] Other 

#### Used versions
* WordPress version: 
* Modula Lite version: 
* Modula PRO version: -
* Albums version: -
* Slider version: -
* Lightbox Slideshow version: -
* Password Protect version: -
* Watermark version: -
* Deeplink version: -
* Right-Click Protection version: -
* Advanced Shortcode version: -
* SpeedUp version: -
* Video version: -

**Comment by cristianraiber** [comment]
Maybe we should also switch in SpeedUP to SPAI API instead of the image optimization one? SPAI has image optimization + responsive 

cc @giucu91

**Comment by cristianraiber** [comment]
Need to hook into a SPAI event that tells us when the image's done being optimised

**Comment by razvanaldea89** [comment]
Seems to be OK now with the latest update to the image size function
