### ISSUE TITLE
Conflict with plugins or themes that use an older version of FancyBox, especially 3.0.47

### ISSUE THREAD

**Issue by razvanaldea89** [WPChill/modula-lite#435]
**Describe the bug**
There are conflicts with themes and plugins that use an older version of FancyBox

**To Reproduce**
1. Go to Plugins and install plugin with FancyBox ( will put an exemple of plugin in the comments )
2. Go to page with Modula Gallery
3. Open Modula Gallery images in lightbox

**Expected behavior**
It should open only 1 lightbox or JS error shouldn't be happening regarding Modula FancyBox and other.

**As a solution** we should try and modify especially the "rel" attribute of the link to something custom so that other FancyBoxes won't be triggered when clicking Modula's link item.

* Which addons do you have installed: 
- [ ] Modula PRO
- [ ] Albums
- [ ] Slider
- [ ] Lightbox Slideshow
- [ ] Password Protect
- [ ] Watermark
- [ ] Deeplink
- [ ] Right-Click Protection
- [ ] Advanced Shortcode
- [ ] SpeedUp
- [ ] Video

* Which browser is affected (or browsers): 
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other 

* Which device is affected (or devices): 
- [ ] Desktop
- [ ] Tablet
- [ ] Mobile
- [ ] Other 

#### Used versions
* WordPress version: 
* Modula Lite version: 
* Modula PRO version: -
* Albums version: -
* Slider version: -
* Lightbox Slideshow version: -
* Password Protect version: -
* Watermark version: -
* Deeplink version: -
* Right-Click Protection version: -
* Advanced Shortcode version: -
* SpeedUp version: -
* Video version: -

**Comment by cristianraiber** [comment]
@razvanaldea89 - please look into this and report back.

**Comment by razvanaldea89** [comment]
@cristianraiber for testing purposes install the EasyFancybox plugin, make a gallery and use it in a page. When trying to open the gallery 2 lightboxes will be opened. one from Modula and one from the other plugin.

**Comment by cristianraiber** [comment]
@razvanaldea89 - can you find a solution to this, please?

**Comment by cristianraiber** [comment]
@razvanaldea89  - status update

**Comment by razvanaldea89** [comment]
Problem still there. A solution would be to replace the `href` attribute of the link with `#` ( or remove completely, but have to see if this doesn't affect other parts of website, such as SEO or markup checking ) and add a custom attribute to the link with the URL of the image ( we need to modify our JS also ), this way we'll be sure that other FancyBox plugins won't intervene with our galleries.

@giucu91 , any thoughts on this one?

**Comment by giucu91** [comment]
Ok, We need to check fancybox ver in order to see what trigger the lightbox. Then we can make a decision.

**Comment by giucu91** [comment]
I think we can close this one.
