### ISSUE TITLE
Border size and custom grid

### ISSUE THREAD

**Issue by razvanaldea89** [WPChill/modula-lite#444]
**Describe the bug**
When setting a border size for the items larger than 0 it will add extra pixels to the item that the script doesn't take into consideration correctly and in the case of custom grid it will place the correctly last image in the row below.

**To Reproduce**
1. Go to gallery to Style tab and add a border size
2. Make gallery type custom grid
3. See in front

**Expected behavior**
The custom grid in the front should relate to the custom grid preview we have in admin.

**Screenshots**

* Which addons do you have installed: 
- [ ] Modula PRO
- [ ] Albums
- [ ] Slider
- [ ] Lightbox Slideshow
- [ ] Password Protect
- [ ] Watermark
- [ ] Deeplink
- [ ] Right-Click Protection
- [ ] Advanced Shortcode
- [ ] SpeedUp
- [ ] Video

* Which browser is affected (or browsers): 
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other 

* Which device is affected (or devices): 
- [ ] Desktop
- [ ] Tablet
- [ ] Mobile
- [ ] Other 

#### Used versions
* WordPress version: 
* Modula Lite version: 
* Modula PRO version: -
* Albums version: -
* Slider version: -
* Lightbox Slideshow version: -
* Password Protect version: -
* Watermark version: -
* Deeplink version: -
* Right-Click Protection version: -
* Advanced Shortcode version: -
* SpeedUp version: -
* Video version: -

**Comment by razvanaldea89** [comment]
As an update, if the image doesn't go on next row look at the width of the container, the last image goes outside it.

**Comment by razvanaldea89** [comment]
Seems to be fixed now. Going to close this

**Comment by cristianraiber** [comment]
@giucu91 - we need a second opinion here. Please close if it's fixed.
