### ISSUE TITLE
Re-work the extensions page

### ISSUE THREAD

**Issue by cristianraiber** [WPChill/modula-lite#447]
![image](https://user-images.githubusercontent.com/7841556/97977607-258a6b00-1dd5-11eb-8ec8-c8485cf9f9c8.png)

**Comment by cristianraiber** [comment]
I really like their approach here. 

- they call it "Modules", we call it "Extensions"
- I like their "Help" tab there. I think we could do something similar where we link to our "Getting Started" guides
- I like their toggle to ON/OFF to disable/enable one extension
- I like the fact that each extension has a direct link to their "Settings" panel inside the main "Settings" page. 
- I like the layout - allows more extensions to be displayed on the same page
- I like the "logo bar" at the top. We could do something similar where we add our logo, our plugin's title and on the right side we could add a "Contact us for support" link and a link to our docs.

**Comment by cristianraiber** [comment]
I also think we should move the "License" tab in the Extensions tab.

**Comment by cristianraiber** [comment]
Also, we currently have a "reload extensions" button but it doesn't say when the last update was done. I think we should display the date and time the last update was done.

**Comment by cristianraiber** [comment]
Ties in with "smart upsells"

**Comment by razvanaldea89** [comment]
@cristianraiber for the addon version we need to modify the response from wp-modula.com when we are getting the extensions list. Parts of the can only be done in the PRO version ( like the toggles and link to settings ). The rest are on their way

**Comment by razvanaldea89** [comment]
The following will be done from the PRO version:

- toggles
- settings link

Version number and possible image will be done when the response from wp-modula.com will be updated ( image att is empty and version att is missing )

**Comment by Florin415** [comment]
Checked the issue , for now or extensions page looks like this : https://prnt.sc/wl2ldq. I will put this issue in tested for now since we will be waiting for the mentioned upgrades by @razvanaldea89  in Modula Pro also. @razvanaldea89  please make a issue with the enhancement tag in Modula Pro and link it to this one so that both can be rested /retested when you implement the rest of the enhancement. @cristianraiber is it alright with you to leave it like the above screenshot for the moment ?

**Comment by razvanaldea89** [comment]
Version needs to be sent with response from wp-modula.com

**Comment by Florin415** [comment]
The Help Tab is missing from the top menu : https://prnt.sc/wni751

**Comment by razvanaldea89** [comment]
Help Tab has transformed to "Documentation" link in the Modula's header

**Comment by Florin415** [comment]
If I change the timezone in WP settings , it will not update the changes in the extensions page when we click the reload extensions button like in this video : https://drive.google.com/file/d/1DWfRHDl6G-e5yS6gEYMHbIjuL6zjqmCy/view

**Comment by cristianraiber** [comment]
This is actually a good catch. We should return the time when the extensions were last updated by taking into account the users' time format display preference. Not everyone ises d/m/Y

**Comment by razvanaldea89** [comment]
Actually is dependent on users time format. What Florin is saying is that it gets the UTC timezone and not users time zone

**Comment by razvanaldea89** [comment]
Timezone / UTC offset should show according to WordPress' settings

**Comment by cristianraiber** [comment]
cc @Florin415

**Comment by Florin415** [comment]
@cristianraiber @razvanaldea89 Indeed the issue seems to be fixed regarding the UTC Time zone as you can see in this video : https://drive.google.com/file/d/1fmOjhK01OWWmtT9vNHc4DKYq3zihUpOv/view ,  but if we select the time zone of a certain location (in my example I selected Bucharest) , it the time will not update : https://drive.google.com/file/d/1urOaTagS_b5Rj6kxbl4yXPJ7i9Z9nRGP/view

**Comment by giucu91** [comment]
![image](https://user-image@razvanaldea89 thubusercontent.com/7580330/106614001-83b12080-6573-11eb-8c8e-ead77259e7cf.png)

@razvanaldea89 toate elementele trebuie sa fie aliniate si la stanga.( butonul de contact us / butonul de reload / extensiile )
butonul de refresh sa fie ultimul si inainte last updated ( deci schimbam ordinea de acum )
trebuie adaugat un buton de read more langa cel de settings.

Revin cu response data de la server

**Comment by giucu91** [comment]
Am aduagat : 
'image'     => $image,
'url'           => $url,
'version'   => $v,

Daca image e gol, pui din plugin. Daca url e gol nu pui read more url
