### ISSUE TITLE
Resize window not working well

### ISSUE THREAD

**Issue by ViSi19** [WPChill/modula-lite#451]
**Describe the bug**
https://drive.google.com/file/d/1ntGT_iz9PDqFkAaBkK1KNW3mjhIBCmGr/view

**Comment by cristianraiber** [comment]
This is regarding the "Columns grid"

**Comment by razvanaldea89** [comment]
Can't reproduce this either ( neither did @Florin415 ). @andyluak test it on Safari please and let us know? Maybe was solved in the meantime

**Comment by andyluak** [comment]
@razvanaldea89 @Florin415 tested on safari it works . I think this issue was fixed on a previous issue with the resize senzor and we probably missed checking this one too .
