### ISSUE TITLE
Modula will not work properly with builders

### ISSUE THREAD

**Issue by Florin415** [WPChill/modula-lite#452]
**Describe the bug**
When I tried to add multiple galleries with, Guttenberg,  Elementor or Beaver builder it will not display the galleries properly. Retested on a live website with only Modula Lite installed , the same issue . 
**To Reproduce**
1. Install Modula and the plugins
2. Create galleries with the builders 
3. Try and add  the galleries to a page (add multiple galleries) 

**Expected behavior**
The galleries to be displayed in the preview properly 
**Screenshots**

Beaver Builder : https://drive.google.com/file/d/1oaH2bzf28kTudrEqxtFNZJjl7ddTsYKI/view
Elementor : https://drive.google.com/file/d/1mNjxGZniKs2OAo0Ph3oBo0KrGvgaom2u/view
Guttenberg : https://drive.google.com/file/d/19C_EznBx1JFCuVByHRTOYEntChgo-Yku/view
Test on live website with only modula lite : https://drive.google.com/file/d/1z9ysAdfiKDH5-fQIujPDUSmTQvmEE5uH/view

It can be tested here : https://wp2.georgeciobanu.com/test-1/

* Which addons do you have installed: 
- [x] Modula PRO Version 
- [x] Albums 
- [ ] Slider
- [ ] Lightbox Slideshow
- [ ] Password Protect
- [ ] Watermark
- [ ] Deeplink
- [ ] Right-Click Protection
- [ ] Advanced Shortcode
- [ ] SpeedUp
- [ ] Video

* Which browser is affected (or browsers): 
- [x] Chrome
- [x] Firefox
- [ ] Safari
- [ ] Other 

* Which device is affected (or devices): 
- [x] Desktop
- [ ] Tablet
- [ ] Mobile
- [ ] Other 

#### Used versions
* WordPress version: 
* Modula Lite version: 2.4.0 (dev) . At the retest I used wp.org version.
* Modula PRO version: -2.4.1 (dev) 
* Albums version: -1.0.6 (dev) 
* Slider version: -
* Lightbox Slideshow version: -
* Password Protect version: -
* Watermark version: -
* Deeplink version: -
* Right-Click Protection version: -
* Advanced Shortcode version: -
* SpeedUp version: -
* Video version: -
* Defaults : 1.0.0 (dev) 
* Whitelabel Version 1.0 (dev -this can be activated or deactivated , it will be the same )

**Comment by razvanaldea89** [comment]
Regarding Elementor, the bug stands true if you put the same gallery twice or more on the page. When the user selects the same gallery from the select input it will reload the first gallery in the DOM and put an empty space the size of the gallery in place of the nth galleries

**Comment by cristianraiber** [comment]
@razvanaldea89 - maybe figure out a way to check if the same gallery isn't already embedded on the page and remove it from the dropdown select? 

Also, I think users should be allowed to display the same gallery, on the same page, multiple times.

**Comment by razvanaldea89** [comment]
@cristianraiber - regarding the first statement, seems like the problem isn't just with the Elementor plugin, same result with Gutenberg is 1 gallery is applied 2 or more times in the same page.

**Comment by razvanaldea89** [comment]
Also, same gallery multiple times in same page won't work

**Comment by Florin415** [comment]
Checked the issue using Modula Lite, this is fixed on Lite, but still happening on Modula Albums, I've made a separate issue for Albums and mark this as tested
