### ISSUE TITLE
Default Hover Effect of Modula-lite does not work in gallery type "Columns"

### ISSUE THREAD

**Issue by ViSi19** [WPChill/modula-lite#454]
**Describe the bug**
Default Hover Effect of Modula-lite does not work in gallery type "Columns"

**To Reproduce**
1. Go to Modula -> Galleries -> select gallery -> set gallery type to "Columns"
2. Open gallery on a page
3. Hover Effect Pufrobo not working

**Expected behavior**

**Screenshots**

* Which addons do you have installed: 
- [ ] Modula PRO
- [ ] Albums
- [ ] Slider
- [ ] Lightbox Slideshow
- [ ] Password Protect
- [ ] Watermark
- [ ] Deeplink
- [ ] Right-Click Protection
- [ ] Advanced Shortcode
- [ ] SpeedUp
- [ ] Video

* Which browser is affected (or browsers): 
- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other 

* Which device is affected (or devices): 
- [ ] Desktop
- [ ] Tablet
- [ ] Mobile
- [ ] Other 

#### Used versions
* WordPress version: 5.5.3
* Modula Lite version: 2.4.0
* Modula PRO version: -
* Albums version: -
* Slider version: -
* Lightbox Slideshow version: -
* Password Protect version: -
* Watermark version: -
* Deeplink version: -
* Right-Click Protection version: -
* Advanced Shortcode version: -
* SpeedUp version: -
* Video version: -

**Comment by Florin415** [comment]
@ViSi19 Tried it now and it seems to be working on my end : https://drive.google.com/file/d/1az11tolMjr4JVZYHLup_qiyEl7yHMv4l/view . Have the dev branch code.

**Comment by cristianraiber** [comment]
@Florin415 - he's referring to the w.org version of Modula Lite  - https://downloads.wordpress.org/plugin/modula-best-grid-gallery.2.4.0.zip

**Comment by Florin415** [comment]
@cristianraiber tried testing with the link above for the zip file  and it's working https://drive.google.com/file/d/1-ZEoNZfpjysbfVN67rl5OJnM8Knc7v0y/view . (only have modula lite installed) . Maybe if someone else could try also :)

**Comment by razvanaldea89** [comment]
Same here, working. But, there is a small problem regarding the transition of the title and social when using Divi builder for example. It has transition set to none, so we need to better CSS target the elements so that the CSS won't be overwritten.
