### ISSUE TITLE
Mention Affileate link in Publish Metabox.

### ISSUE THREAD

**Issue by giucu91** [WPChill/modula-lite#455]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Add a link in publish metabox "Earn money with Modula" that will redirect user, in a new tab, to /wp-admin/edit.php?post_type=modula-gallery&page=modula&modula-tab=affiliate.

The design should be like the "CTRL + S" section but the link should be blue.

**Comment by cristianraiber** [comment]
Ties in with: #290

**Comment by giucu91** [comment]
we removed this functionality.
