### ISSUE TITLE
Divi does not upload the settings after the change from the Modula dashbord

### ISSUE THREAD

**Issue by ViSi19** [WPChill/modula-lite#457]
**Describe the bug**
If you put a gallery on the page with Divi then something changes, any change in the Modula dashboard will not be updated on the page.

**To Reproduce**
1. Go to Modula, create a gallery post on the Divi Page. 
2. Modify something in Modula dashbord, then click on "update"
3. On page nothing change.

**Expected behavior**
Update the settings on the page

* Which addons do you have installed: 
- [x] Modula Lite

* Which browser is affected (or browsers): 
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other 
-[x] all 

* Which device is affected (or devices): 
- [ ] Desktop
- [ ] Tablet
- [ ] Mobile
- [ ] Other 
-[x] all 

#### Used versions
* WordPress version: 5.3.3
* Modula Lite version: - 2.4.0
* Modula PRO version: -
* Albums version: -
* Slider version: -
* Lightbox Slideshow version: -
* Password Protect version: -
* Watermark version: -
* Deeplink version: -
* Right-Click Protection version: -
* Advanced Shortcode version: -
* SpeedUp version: -
* Video version: -

**Comment by razvanaldea89** [comment]
@ViSi19 did you update/refresh the page where you are editing with Divi? Not just "Save" using the save button, but update/refresh the page. The save button just sends data to be saved, does not reload the page / update outside saved data.

**Comment by razvanaldea89** [comment]
Seems to work. Works on @ViSi19 's end now too
