### ISSUE TITLE
Color pickers will not work properly with the Avada theme

### ISSUE THREAD

**Issue by Florin415** [WPChill/modula-lite#459]
**Describe the bug**
If we go to the social tab and try to pick a color for them, the color picker will not be displayed properly.

**To Reproduce**
1. Install Avanda theme
2. Go to the social tab and try to pick a color for the social icons.

**Expected behavior**
The color picker not to float

**Screenshots**
https://prnt.sc/vyzatz
https://prnt.sc/vyzgub
https://prnt.sc/vyzhki
https://prnt.sc/vyzhyb
https://prnt.sc/vyzi42
https://prnt.sc/vyzibu
https://prnt.sc/vyzio7
https://prnt.sc/vyziv2

* Which addons do you have installed: 
- [x] Modula PRO
- [ ] Albums
- [ ] Slider
- [ ] Lightbox Slideshow
- [ ] Password Protect
- [ ] Watermark
- [ ] Deeplink
- [ ] Right-Click Protection
- [ ] Advanced Shortcode
- [ ] SpeedUp
- [ ] Video

* Which browser is affected (or browsers): 
- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other 

* Which device is affected (or devices): 
- [x] Desktop
- [ ] Tablet
- [ ] Mobile
- [ ] Other 

#### Used versions
* WordPress version: 5.6
* Modula Lite version: 2.4.1 (dev)
* Modula PRO version: - 2.4.2(dev)
* Albums version: -
* Slider version: -
* Lightbox Slideshow version: -
* Password Protect version: -
* Watermark version: -
* Deeplink version: -
* Right-Click Protection version: -
* Advanced Shortcode version: -
* SpeedUp version: -
* Video version: -

**Comment by razvanaldea89** [comment]
Extra color picker palletes ( we are working in 8 color pallets with 255 width, Avada was adding 4 extra palletes at 350  ) are hidden so the Modula color picker could be displayed properly

**Comment by Florin415** [comment]
We are still having this issue : https://drive.google.com/file/d/1eJkt8mPKApiLQCj1ayvzlsysbUqStAAM/view

**Comment by Florin415** [comment]
Retested the issue, it still happens on Edge , Chrome and Opera. On Mozila it's working : https://prnt.sc/wj4qpa
