### ISSUE TITLE
Modula Gallery name not fully displayed in the preview when we add it to a new page

### ISSUE THREAD

**Issue by Florin415** [WPChill/modula-lite#460]
**Describe the bug**
If we add the gallery to a page, in the preview will not see the gallery's full name properly

**To Reproduce**
1. Have Modula lite and Pro installed
2. Create a gallery and add it to a new page
3. You will see that the full name of the gallery will not be displayed 

**Expected behavior**
To have the full name displayed in the dropdown 

**Screenshots**
https://prnt.sc/vz2vlh

* Which addons do you have installed: 
- [x] Modula PRO
- [ ] Albums
- [ ] Slider
- [ ] Lightbox Slideshow
- [ ] Password Protect
- [ ] Watermark
- [ ] Deeplink
- [ ] Right-Click Protection
- [ ] Advanced Shortcode
- [ ] SpeedUp
- [ ] Video

* Which browser is affected (or browsers): 
- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other 

* Which device is affected (or devices): 
- [x] Desktop
- [ ] Tablet
- [ ] Mobile
- [ ] Other 

#### Used versions
* WordPress version: 5.6
* Modula Lite version: 2.4.1 (dev)
* Modula PRO version: -2.4.2(dev)
* Albums version: -
* Slider version: -
* Lightbox Slideshow version: -
* Password Protect version: -
* Watermark version: -
* Deeplink version: -
* Right-Click Protection version: -
* Advanced Shortcode version: -
* SpeedUp version: -
* Video version: -

**Comment by Florin415** [comment]
Issue is still present on Chrome, Edge,Opera : https://prnt.sc/wl0ovi . On firefox it's working : https://prnt.sc/wl0p7x

**Comment by razvanaldea89** [comment]
@andyluak can you please test this also with Safari?

**Comment by Florin415** [comment]
Tested with Opera, Mozila,Edge,Chrome, now the issue seams to be fixed, @andyluak when you have time please also test it on Safari (lite branch 2.4.2 dev and pro branch 2.4.4)

**Comment by andyluak** [comment]
Tested on safari also and it works .
