### ISSUE TITLE
Modula Gallery not displayed properly in the preview when we add it to a new page

### ISSUE THREAD

**Issue by Florin415** [WPChill/modula-lite#461]
**Describe the bug**
If we add a gallery with many images to a page, we will see that the last image will exit the gallery

**To Reproduce**
1. Create a new gallery
2. Add it to a page
3. In preview you will see that the images will exit the gallery preview box 

**Expected behavior**
The images to fit the preview box

**Screenshots**
https://prnt.sc/vz3442

* Which addons do you have installed: 
- [x] Modula PRO
- [ ] Albums
- [ ] Slider
- [ ] Lightbox Slideshow
- [ ] Password Protect
- [ ] Watermark
- [ ] Deeplink
- [ ] Right-Click Protection
- [ ] Advanced Shortcode
- [ ] SpeedUp
- [ ] Video

* Which browser is affected (or browsers): 
- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other 

* Which device is affected (or devices): 
- [x] Desktop
- [ ] Tablet
- [ ] Mobile
- [ ] Other 

#### Used versions
* WordPress version: 5.6
* Modula Lite version: 2.4.1 (dev)
* Modula PRO version: -2.4.2(dev)
* Albums version: -
* Slider version: -
* Lightbox Slideshow version: -
* Password Protect version: -
* Watermark version: -
* Deeplink version: -
* Right-Click Protection version: -
* Advanced Shortcode version: -
* SpeedUp version: -
* Video version: -

**Comment by razvanaldea89** [comment]
Also, here, when adding the Gutenberg block, the text in the select isn't displayed OK

**Comment by razvanaldea89** [comment]
![image](https://user-images.githubusercontent.com/44024114/101748049-b93a1000-3ad4-11eb-8c59-40318fa8d91d.png)

**Comment by razvanaldea89** [comment]
@andyluak is this fixed now? Can be tested?

**Comment by andyluak** [comment]
Yes @razvanaldea89 . it was fixed a few commits ago , I must have missed adding the need testing on it .
