### ISSUE TITLE
Redo the features comparison page between Modula LITE & Modula PRO

### ISSUE THREAD

**Issue by razvanaldea89** [WPChill/modula-lite#463]

**Comment by cristianraiber** [comment]
This needs to happen in the backend of Modula. Ties in with "smart upsells"

**Comment by razvanaldea89** [comment]
@giucu91 Please take a look at this also

**Comment by Florin415** [comment]
@razvanaldea89 I think this link : https://prnt.sc/wl2bze , should send the user to https://wp-modula.com/pricing/ , for the moment it send the user to : https://wp-modula.com/?utm_source=modula-lite&utm_medium=about-page&utm_campaign=upsell . Will leave the need testing label until @giucu91 will look over it also and tell us where the link should lead .

**Comment by cristianraiber** [comment]
This is not the proper way to go. We're looking to remove all of the 'pro' wording from our upsells. 

See: 
- https://github.com/WPChill/modula-theme/issues/38

**Comment by razvanaldea89** [comment]
Here we could make it some sort of a blog post, with the comparison between those two, not just throw data there.

**Comment by cristianraiber** [comment]
> Here we could make it some sort of a blog post, with the comparison between those two, not just throw data there.

That's a good idea!

**Comment by giucu91** [comment]
![image](https://user-images.githubusercontent.com/7580330/106855325-67bd9400-66c5-11eb-996c-2a9823bb7c60.png)

Maybe put Free and Premium ? @cristianraiber 
Also we have 2 hover effects : Pufbro and none.

**Comment by cristianraiber** [comment]
I think we should use the lite vs pro comparison table we currently have on our pricing page. It's better explained as well as has most of the information correct. 

@giucu91 - yes, let's go with free and premium
