### ISSUE TITLE
Put a what's new on the about page

### ISSUE THREAD

**Issue by razvanaldea89** [WPChill/modula-lite#466]
Tell users what is new on the about page, not only what is fixed and enhanced ( i.e. : what new addons are available, or what new functionalities exist in the PRO version and addons ), so that users can now what is going on on the whole Modula Project.

This is in regards to the clients feedback : 
`Client feedback: I would love the ability to setup a template. I use the same settings for each gallery but have to go through all the menus and select my preferences everytime I create a new gallery blog post. Imagine being able to use one click to select a specific template and the job is done..` where that functionality exists in Modula's addon Defaults

**Comment by cristianraiber** [comment]
How about sending these types of requests into HelpScout and replying from there with a canned (pre-saved) response ? Basically, notifying them personally. 

On this note, we could, potentially, also improve our uninstall popup and let users know about the features they'll be missing out on IF they uninstall.

**Comment by cristianraiber** [comment]
Could tie in with "smart upsells"

**Comment by cristianraiber** [comment]
@razvanaldea89 - status update?

**Comment by razvanaldea89** [comment]
No implementation has been made, yet.  Could you please detail the `requests to HelpScout` part? Maybe it would be better to have a call with @giucu91 also and discuss this.

**Comment by cristianraiber** [comment]
@razvanaldea89 - I was referring to using HelpScout's Beacon functionality and loading it in our PRO plugins. So users could talk to us directly from their backends

**Comment by giucu91** [comment]
It's a plain text there, we can add whatever we want.
