### ISSUE TITLE
Cannot create Album galleries if I have the future update on the site.

### ISSUE THREAD

**Issue by Florin415** [WPChill/modula-lite#473]
**Describe the bug**
I installed the future update on a local, installed modula pro from wp-modula.com and also albums (tried also with modula pro and albums dev branches ) but I could not create albums anymore.

**To Reproduce**
1. Install Modula lite branch 2.4.2 - dev
2. Install modula pro and  albums
3. Try to create a album 

**Expected behavior**
To be able to create albums 
**Screenshots**
https://drive.google.com/file/d/1y9Nlfs1alqCdmz3NFZdspmWfckVKSdlg/view

Screenshots of the console errors : https://prnt.sc/wib6ik

* Which addons do you have installed: 
- [x] Modula PRO
- [x] Albums
- [ ] Slider
- [ ] Lightbox Slideshow
- [ ] Password Protect
- [ ] Watermark
- [ ] Deeplink
- [ ] Right-Click Protection
- [ ] Advanced Shortcode
- [ ] SpeedUp
- [ ] Video

* Which browser is affected (or browsers): 
- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other 

* Which device is affected (or devices): 
- [x] Desktop
- [ ] Tablet
- [ ] Mobile
- [ ] Other 

#### Used versions
* WordPress version: 5.6
* Modula Lite version: 2.4.2 - dev
* Modula PRO version: -wp-modula.com (dev branch as well ) 
* Albums version: -wp-modula.com (dev branch as well ) 
* Slider version: -
* Lightbox Slideshow version: -
* Password Protect version: -
* Watermark version: -
* Deeplink version: -
* Right-Click Protection version: -
* Advanced Shortcode version: -
* SpeedUp version: -
* Video version: -

**Comment by razvanaldea89** [comment]
This should be moved to Albums

**Comment by razvanaldea89** [comment]
Also, @Florin415 could you please get latest Albums and test again? Modula's ResizeSensor had been renamed and an update has been issued to Albums
