### ISSUE TITLE
option to enable/disable autosave

### ISSUE THREAD

**Issue by mplusb** [WPChill/modula-lite#474]
**Is your feature request related to a problem? Please describe.**
feedback: it automatically saves what I've done when I don't want it saved

**Describe the solution you'd like**
a button to turn on/off this feature

**Comment by mplusb** [comment]
+1

**Comment by cristianraiber** [comment]
+1 https://wordpress.org/support/topic/pretty-but-one-issue/

**Comment by beatricelucaci** [comment]
+1 https://secure.helpscout.net/conversation/2064696879/51549?folderId=4656050

**Comment by mplusb** [comment]
+1  omg PLEASE stop the mandatory auto-saving when editing a gallery, especially as there in on undo option. I have to go to my webhost and roll-back my entire website EVERY TIME

**Comment by razvanaldea89** [comment]
Should be either default to OFF or, if it's a first install can be left on ON. @cristianraiber @giucu91 OFF/ON by default? If we directly put on OFF it would possibly affect some users that want and use this functionality.

**Comment by giucu91** [comment]
@TeoAlex add an option to disable autosaving. default On

**Comment by TeoAlex** [comment]
A change was made so the images are now being saved on gallery update not every time an image was changed/removed/modified so this should fix the autosave issues.
