### ISSUE TITLE
image dimensions misses a 'p' in 'px'

### ISSUE THREAD

**Issue by mplusb** [WPChill/modula-lite#478]
**Describe the bug**
image dimensions misses a 'p' in 'px'

**To Reproduce**
1. Go to General > Columns > Image size > Custom size > image dimensions.

**Screenshots**
<img width="956" alt="Screenshot 2021-01-26 at 11 06 16" src="https://user-images.githubusercontent.com/26008574/105824135-a4eb9d00-5fc6-11eb-94ef-8aae82b9234c.png">

#### Used versions
* WordPress version: 5.6
* Modula Lite version: 2.4.1

**Comment by razvanaldea89** [comment]
Actually not quite... it is meant for seize x seize in pixels. 

![image](https://user-images.githubusercontent.com/44024114/106134413-2aaa4c80-616f-11eb-9d33-267c85614a15.png)

But your are right, we should come with a different approach on this one
