### ISSUE TITLE
the ability to show a gallery in the search results if you search by an image's title/description

### ISSUE THREAD

**Issue by mplusb** [WPChill/modula-lite#484]
**Is your feature request related to a problem? Please describe.**
the ability to show a gallery in the search results if you search by an image's title/description

**Additional context**
How can I ensure my images show up in on site search? I just uploaded a few hundred photos, all with full descriptive titles and nothing seems to show up in search. I would have thought with the SEO deeplinking it would make sense to also be able to search and link to images within the site?

**Comment by giucu91** [comment]
This should be handle by a theme, not our plugin.
