### ISSUE TITLE
Add a Welcome page

### ISSUE THREAD

**Issue by razvanaldea89** [WPChill/modula-lite#485]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
I think it will be a great enhancement if we add a Welcome page where the following data should be sent:

- notifications of all kind, including rating and plugin/addons update
- known compatibility issues with different themes/plugins
- known major bugs with WordPress / Themes / Plugins
- in the case of the PRO version and Add-ons compatibility issues between Modula's items ( this one regarding the updates, if the user updates one then the user should update all corresponding items, especially if there are some issues between the versions )
- info regarding Modula like galleries number, number of total images used, Modula & Co. versions
- link to the About page if the user wants to see again what was fixed / enhanced
- enhancements that are planned to be introduced in the next couple of updates ( maybe add plugin version so the user knows when to expect the enhancement should be deployed? )
-  planned updates ? ( I know this one is not quite achievable, yet!  )

**Describe alternatives you've considered**
-

**Additional context**
@cristianraiber @giucu91 @andyluak @mplusb  any thoughts on this one? Think this is a good thing, user will know what to expect from the plugin in regards with compatibility and functionality, will know if there are problems with their current installation ( conflicts between plugins/theme - think this one is extremely beneficent for the support team ), know what they'll get next and so on.

**Comment by cristianraiber** [comment]
@razvanaldea89 - I think this is a great idea. This does need more exploration in terms of design and how it'll be presented to the user, but I think it has a lot of potential. 

Side note: something similar is implemented in Yoast. They have a centralised way of handling their notifications.

**Comment by giucu91** [comment]
we will implement https://github.com/WPChill/modula-lite/issues/800
