### ISSUE TITLE
Pagina de Migrate

### ISSUE THREAD

**Issue by andyluak** [WPChill/modula-lite#493]
**Describe the bug**
 - Tabul de Migrate mutat din pagina de Settings si mutat intro pagina separata
 - 
**Screenshots**

![image](https://user-images.githubusercontent.com/49715292/107490866-1fa1e400-6b93-11eb-85d4-bda43e65d381.png)

* Which addons do you have installed: 
- [ ] Modula PRO
- [ ] Albums
- [ ] Slider
- [ ] Lightbox Slideshow
- [ ] Password Protect
- [ ] Watermark
- [ ] Deeplink
- [ ] Right-Click Protection
- [ ] Advanced Shortcode
- [ ] SpeedUp
- [ ] Video

* Which browser is affected (or browsers): 
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other 

* Which device is affected (or devices): 
- [ ] Desktop
- [ ] Tablet
- [ ] Mobile
- [ ] Other 

#### Used versions
* WordPress version: 
* Modula Lite version: 
* Modula PRO version: -
* Albums version: -
* Slider version: -
* Lightbox Slideshow version: -
* Password Protect version: -
* Watermark version: -
* Deeplink version: -
* Right-Click Protection version: -
* Advanced Shortcode version: -
* SpeedUp version: -
* Video version: -

**Comment by giucu91** [comment]
am rezolvat cumva 
<img width="1181" alt="image" src="https://github.com/WPChill/modula-lite/assets/7580330/f7f6406d-d04b-4ee1-a3c0-8887fd8a918d">
