### ISSUE TITLE
Redo the "Misc" tab in Settings

### ISSUE THREAD

**Issue by razvanaldea89** [WPChill/modula-lite#494]
**Describe the bug**
Better explanation what the settings do and add more headings because the page has not related settings. 

**Screenshots**
![image](https://user-images.githubusercontent.com/44024114/107491289-9b9c2c00-6b93-11eb-819d-7516fc4096e1.png)

**Comment by giucu91** [comment]
<img width="1044" alt="image" src="https://github.com/WPChill/modula-lite/assets/7580330/efb589c1-0a0b-4f8a-adcf-cb149596b724">
we have headings now
