### ISSUE TITLE
does not work to share on LinkedIn

### ISSUE THREAD

**Issue by mplusb** [WPChill/modula-lite#503]
**Describe the bug**
If you turn on social links on hover and then try to share on LinkedIn it throws an error

**To Reproduce**
1. Go to your gallery > social links > turn on LinkedIn
2. Then try to share an image on LinkedIn
3. See error

**Screenshots**
<img width="1192" alt="Screenshot 2021-02-15 at 13 31 56" src="https://user-images.githubusercontent.com/26008574/107941485-72640d00-6f92-11eb-9654-31bd57fc587d.png">
Can also be seen on our demo: https://modula.gallery/blog/modula-gallery/enable-social-icons/

#### Used versions
* WordPress version: 5.6.1
* Modula Lite version: 2.4.1

**Comment by razvanaldea89** [comment]
This is fixed now.
