### ISSUE TITLE
Modula does not work in a Divi slider widget 

### ISSUE THREAD

**Issue by mplusb** [WPChill/modula-lite#505]
**Describe the bug**
add modula's shortcode within a Divi slider block and it will only work for the first slide.
The second slide will not display the second gallery

**To Reproduce**
1. Install Divi > edit a page using Divi's page builder 
2. Choose the slider module
3. for each slide add a gallery

https://secure.helpscout.net/conversation/1419679319/35369?folderId=1289779

#### Used versions
* WordPress version: 5.6.1
* Modula Lite version: 2.4.1

**Comment by mplusb** [comment]
seems to work fine now with modula 2.7.7 and modula pro 2.6.5 @TeoAlex

**Comment by TeoAlex** [comment]
Yes, it seems like the issue was fixed in a previous update.
