### ISSUE TITLE
the gallery does not keep its layout when using Modula's Gutenberg block

### ISSUE THREAD

**Issue by mplusb** [WPChill/modula-lite#506]
**Describe the bug**
the gallery just does not look correct in the live preview of Wordpress. I'm including a screenshot of what it looks like in Wordpress editor
<img width="1197" alt="Screenshot 2021-02-15 at 14 10 39" src="https://user-images.githubusercontent.com/26008574/107945002-a988ed00-6f97-11eb-8bd3-1806d6f100a2.png">
And how it should look:
<img width="1278" alt="Screenshot 2021-02-15 at 14 11 00" src="https://user-images.githubusercontent.com/26008574/107945017-af7ece00-6f97-11eb-8881-8d32d151f344.png">

**To Reproduce**
1. create a gallery using Custom grid for example, then add it on a page using Modula's block.
2. It does not keep the layout.

**Expected behavior**
Should keep the layout

#### Used versions
* WordPress version: 5.6.1
* Modula Lite version: 2.4.1

**Comment by mplusb** [comment]
https://secure.helpscout.net/conversation/1414032168/35188?folderId=1289779

**Comment by giucu91** [comment]
This was fixed.
