### ISSUE TITLE
Gallery types

### ISSUE THREAD

**Issue by razvanaldea89** [WPChill/modula-lite#509]
**Describe the bug**

Add Justified Gallery in "Gallery type" and "Columns" will be renamed "Masonry" and the second select will only contain the columns number.
Do backwards compatibility for gallery types.

**Comment by giucu91** [comment]
@razvanaldea89 @cristianraiber do you still want this ?

**Comment by razvanaldea89** [comment]
From my point of view it can remain as it is, seems that people did not complain about the naming.

**Comment by cristianraiber** [comment]
We can close this, seems like no one is complaining about it.
