### ISSUE TITLE
Remove lightbox upsell 

### ISSUE THREAD

**Issue by andyluak** [WPChill/modula-lite#518]
**Describe the bug**
Remove lightbox upsell when atachment or no link selected . 

**Screenshots**
![image](https://user-images.githubusercontent.com/49715292/108046620-7e60d500-704d-11eb-824f-6ef75a8e38ad.png)

* Which addons do you have installed: 
- [ ] Modula PRO
- [ ] Albums
- [ ] Slider
- [ ] Lightbox Slideshow
- [ ] Password Protect
- [ ] Watermark
- [ ] Deeplink
- [ ] Right-Click Protection
- [ ] Advanced Shortcode
- [ ] SpeedUp
- [ ] Video

* Which browser is affected (or browsers): 
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other 

* Which device is affected (or devices): 
- [ ] Desktop
- [ ] Tablet
- [ ] Mobile
- [ ] Other 

#### Used versions
* WordPress version: 
* Modula Lite version: 
* Modula PRO version: -
* Albums version: -
* Slider version: -
* Lightbox Slideshow version: -
* Password Protect version: -
* Watermark version: -
* Deeplink version: -
* Right-Click Protection version: -
* Advanced Shortcode version: -
* SpeedUp version: -
* Video version: -

**Comment by giucu91** [comment]
We will keep the upsells for all options.
