### ISSUE TITLE
Lazy load on feed images not appearing

### ISSUE THREAD

**Issue by razvanaldea89** [WPChill/modula-lite#527]
**Describe the bug**
If is a feed and lazy load is enabled on gallery, the images won't show as the src is not present.  We should check if it is feed and disable the part where we unset the sec for lazy load.

**To Reproduce**

**Expected behavior**

**Screenshots**

* Which addons do you have installed: 
- [ ] Modula PRO
- [ ] Albums
- [ ] Slider
- [ ] Lightbox Slideshow
- [ ] Password Protect
- [ ] Watermark
- [ ] Deeplink
- [ ] Right-Click Protection
- [ ] Advanced Shortcode
- [ ] SpeedUp
- [ ] Video

* Which browser is affected (or browsers): 
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other 

* Which device is affected (or devices): 
- [ ] Desktop
- [ ] Tablet
- [ ] Mobile
- [ ] Other 

#### Used versions
* WordPress version: 
* Modula Lite version: 
* Modula PRO version: -
* Albums version: -
* Slider version: -
* Lightbox Slideshow version: -
* Password Protect version: -
* Watermark version: -
* Deeplink version: -
* Right-Click Protection version: -
* Advanced Shortcode version: -
* SpeedUp version: -
* Video version: -

**Comment by giucu91** [comment]
@razvanaldea89 what is a feed ?
