### ISSUE TITLE
Function is_plugin_active is not defined

### ISSUE THREAD

**Issue by giucu91** [WPChill/modula-lite#534]
**Describe the bug**
Function is_plugin_active is not defined on frontend. We shoul include include_once( ABSPATH . 'wp-admin/includes/plugin.php' );

But the compatibility should be only on backend because these checks will slow down clients websites

**Screenshots**
![image](https://user-images.githubusercontent.com/7580330/110494955-badb9a00-80fc-11eb-9fb1-efb86a1eee4b.png)

* Which addons do you have installed: 
- [ ] Modula PRO
- [ ] Albums
- [ ] Slider
- [ ] Lightbox Slideshow
- [ ] Password Protect
- [ ] Watermark
- [ ] Deeplink
- [ ] Right-Click Protection
- [ ] Advanced Shortcode
- [ ] SpeedUp
- [ ] Video

* Which browser is affected (or browsers): 
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other 

* Which device is affected (or devices): 
- [ ] Desktop
- [ ] Tablet
- [ ] Mobile
- [ ] Other 

#### Used versions
* WordPress version: 
* Modula Lite version: 
* Modula PRO version: -
* Albums version: -
* Slider version: -
* Lightbox Slideshow version: -
* Password Protect version: -
* Watermark version: -
* Deeplink version: -
* Right-Click Protection version: -
* Advanced Shortcode version: -
* SpeedUp version: -
* Video version: -

**Comment by razvanaldea89** [comment]
@giucu91 The problem is that we need to remove a script and add something to the front end gallery config so that the gallery will render correctly.
