### ISSUE TITLE
Check why gallery is not initialize

### ISSUE THREAD

**Issue by giucu91** [WPChill/modula-lite#535]
**Describe the bug**
Gallery does not load if it’s hidden

https://wordpress.org/support/topic/gallery-does-not-load-if-its-hidden/#utm_medium=referral&utm_source=facebook.com&utm_content=social

* Which addons do you have installed: 
- [ ] Modula PRO
- [ ] Albums
- [ ] Slider
- [ ] Lightbox Slideshow
- [ ] Password Protect
- [ ] Watermark
- [ ] Deeplink
- [ ] Right-Click Protection
- [ ] Advanced Shortcode
- [ ] SpeedUp
- [ ] Video

* Which browser is affected (or browsers): 
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other 

* Which device is affected (or devices): 
- [ ] Desktop
- [ ] Tablet
- [ ] Mobile
- [ ] Other 

#### Used versions
* WordPress version: 
* Modula Lite version: 
* Modula PRO version: -
* Albums version: -
* Slider version: -
* Lightbox Slideshow version: -
* Password Protect version: -
* Watermark version: -
* Deeplink version: -
* Right-Click Protection version: -
* Advanced Shortcode version: -
* SpeedUp version: -
* Video version: -

**Comment by razvanaldea89** [comment]
@giucu91 Gallery is initialized but the script doesn't know how to arrange the images and, depending on gallery type, the size of the images. A reset would be needed for the gallery to be displayed correctly.
