### ISSUE TITLE
Add tab link to Modula About page in the Settings page

### ISSUE THREAD

**Issue by razvanaldea89** [WPChill/modula-lite#543]

**Comment by giucu91** [comment]
@razvanaldea89 can you describe more ?

**Comment by razvanaldea89** [comment]
Add another tab linking to the About page here:

![image](https://user-images.githubusercontent.com/44024114/131637914-8e1d2876-fede-485e-b5d5-b2b6a6616e69.png)

**Comment by giucu91** [comment]
@razvanaldea89 put the link in branding header
![image](https://user-images.githubusercontent.com/7580330/132454816-b3a1f5ae-78de-4292-a8ea-69d4dd083bbd.png)

**Comment by cristianraiber** [comment]
Doesn't make sense to have it there. It should be in the "Welcome" page as a sub-tab, re-named to Changelog.

**Comment by cristianraiber** [comment]
Related to: #633
