### ISSUE TITLE
 Problem with unchanging image size

### ISSUE THREAD

**Issue by mplusb** [WPChill/modula-lite#545]
**Describe the bug**
I have a problem with the image size option when I edit my gallery. I set the images size to 2048 x2048. But when I update the gallery, it returns to image size : custom. Why is this occurring in this gallery and what do I do to fix this?

**To Reproduce**

**Expected behavior**

**Screenshots**

* Which addons do you have installed: 
- [ ] Modula PRO
- [ ] Albums
- [ ] Slider
- [ ] Lightbox Slideshow
- [ ] Password Protect
- [ ] Watermark
- [ ] Deeplink
- [ ] Right-Click Protection
- [ ] Advanced Shortcode
- [ ] SpeedUp
- [ ] Video

* Which browser is affected (or browsers): 
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other 

* Which device is affected (or devices): 
- [ ] Desktop
- [ ] Tablet
- [ ] Mobile
- [ ] Other 

#### Used versions
* WordPress version: 
* Modula Lite version: 
* Modula PRO version: -
* Albums version: -
* Slider version: -
* Lightbox Slideshow version: -
* Password Protect version: -
* Watermark version: -
* Deeplink version: -
* Right-Click Protection version: -
* Advanced Shortcode version: -
* SpeedUp version: -
* Video version: -

https://secure.helpscout.net/conversation/1472845478/36925?folderId=1289779

**Comment by giucu91** [comment]
Is posible to be resolved in 2.5.1 . WE should check
