### ISSUE TITLE
Upsell to Modula Pro

### ISSUE THREAD

**Issue by BostanicaElena** [WPChill/modula-lite#552]
**Is your feature request related to a problem? Please describe.**
When installing Modula Lite in Wordpress, there is no mention of Modula Pro version.

**Describe the solution you'd like**
Given that the upgrade can be done only on the website, we can put a link from the plugin to the pricing page https://wp-modula.com/pricing/

**Additional context**
Example provided in the screenshot attached (from another plug-in).
![Capture](https://user-images.githubusercontent.com/82649745/115010072-a89c0b00-9eb5-11eb-8746-725cda4b9f4d.PNG)

**Comment by cristianraiber** [comment]
Extra context: this happens in the plugin's quick action settings. 

![image](https://user-images.githubusercontent.com/7841556/115010401-0e889280-9eb6-11eb-8c0b-b62928cf1d18.png)

**Comment by giucu91** [comment]
@cristianraiber @BostanicaElena maybe sending the user to lite vs pro page ?

**Comment by cristianraiber** [comment]
@giucu91 - that works.
