### ISSUE TITLE
Add a reset metabox positioning button

### ISSUE THREAD

**Issue by razvanaldea89** [WPChill/modula-lite#553]
**Is your feature request related to a problem? Please describe.**
When users move the metaboxes, sometimes it is very hard to put them back to how they should be

**Describe the solution you'd like**
Put a reset button so everything should reset back to normal

**Comment by giucu91** [comment]
I think the better solution will be to fix the gallery metabox.

**Comment by razvanaldea89** [comment]
https://wordpress.stackexchange.com/questions/2474/disable-dragging-of-meta-boxes should try with the `wp_deregister_script` so that we won't add another script to the page

**Comment by TeoAlex** [comment]
https://github.com/WPChill/modula-lite/commit/06a6eb9115c6d654a66842af9e4a24bacf4a3bd4
