### ISSUE TITLE
If search only, remove the "down arrow" from search field

### ISSUE THREAD

**Issue by razvanaldea89** [WPChill/modula-lite#566]
**Describe the bug**
If we only search for galleries then the down arrow is pointless.
**To Reproduce**
1. Add Modula Gutenberg block in page
2. See Gallery settings 

**Screenshots**
![image](https://user-images.githubusercontent.com/44024114/117771051-5e047900-b23e-11eb-8296-76a07e831ccd.png)

**Comment by giucu91** [comment]
we also have dropdown there
