### ISSUE TITLE
When the shortcode is wrapped with the wpautop() function, lightboxes won't open

### ISSUE THREAD

**Issue by beatricelucaci** [WPChill/modula-lite#577]
**Describe the bug**
When a modula gallery is embedded in content using a shortcode, and that short code wrapped with the wpautop() function, the lightbox fails
https://secure.helpscout.net/conversation/1538970962/38621?folderId=4656050

* Which device is affected (or devices): 
- [x] Desktop
- [ ] Tablet
- [ ] Mobile
- [ ] Other

**Comment by razvanaldea89** [comment]
Seems like we have lots of double line breaks, clearing those will solve our problem ( human file readability will be lowered but problems with wpautop will reduce ). This is also available for the PRO version and Slider extension.

**Comment by giucu91** [comment]
I don't think we can make it work with wpautop.
