### ISSUE TITLE
The gutter expands on higher resolutions

### ISSUE THREAD

**Issue by beatricelucaci** [WPChill/modula-lite#581]
**Describe the bug**
The gutter expands on higher resolutions
 I've adjusted the gutter to 80 px, but neither the middle gutter nor left & right margins are of this width... what to do?
I'm using a Lenovo X1 Yoga, with a resolution of 2560x1440 and this
Chrome Version
91.0.4472.124 (Official Build) (64-bit)

https://secure.helpscout.net/conversation/1557029273/39143?folderId=4656050

* Which browser is affected (or browsers): 
- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other 

* Which device is affected (or devices): 
- [x] Desktop
- [ ] Tablet
- [ ] Mobile
- [ ] Other

**Comment by giucu91** [comment]
@razvanaldea89 check if this happens because the images are to small.

**Comment by razvanaldea89** [comment]
@giucu91 on bigger monitors or higher resolutions, like the client has, the images maximum width tend to be it's own width ( so a image with 1020x666 px will have a maximum width of 1020px, it won't follow it's parent element ). In the client's case, the image has 1120px width ( so 2240px from both images ), leaving us with ~320px space in between the images.

**Comment by razvanaldea89** [comment]
Think a general fix, putting` .modula-item-content` and `img.pic` with `width:100%` will do the trick for all gallery types ( generally the width is set to `.modula-item` and the script puts style directly to the image element, so this should not interfere with them )
