### ISSUE TITLE
Add the options from tracking to uninstall process

### ISSUE THREAD

**Issue by razvanaldea89** [WPChill/modula-lite#591]
**Describe the bug**
Options from tracking, like `wisdom_deactivation_reason_` and `wisdom_deactivation_details_`. Search `includes/tracking/class-plugin-usage-tracker.php` file for options and transients

**Comment by giucu91** [comment]
maybe don't save these information on db.

**Comment by razvanaldea89** [comment]
Those options are part of the Wisdom Plugin and may trigger conflicts if we don't save them in the db.
