### ISSUE TITLE
add image to sitemap.xml yoast

### ISSUE THREAD

**Issue by giucu91** [WPChill/modula-lite#594]
We can make an integration with Yoast SEO in order to check if a page/post have an modula shortcode.

https://yoast.com/help/images-in-the-xml-sitemap/

**Comment by mplusb** [comment]
+1

**Comment by beatricelucaci** [comment]
+1

**Comment by beatricelucaci** [comment]
related issue here: https://github.com/WPChill/modula-lite/issues/794
