### ISSUE TITLE
image size bug

### ISSUE THREAD

**Issue by mplusb** [WPChill/modula-lite#595]
**Describe the bug**
Error displaying on certain images on hover: 
Notice: Undefined index: thumbnail in /public_html/wp-content/plugins/modula-best-grid-gallery/includes/public/modula-helper-functions.php on line 331

Notice: Trying to access array offset on value of type null in /public_html/wp-content/plugins/modula-best-grid-gallery/includes/public/modula-helper-functions.php on line 331

**To Reproduce**
1. add images 300x300
2. put image size thumbnail 300x300
3. See error

**Expected behavior**

**Screenshots**

* Which addons do you have installed: 
- [ ] Modula PRO
- [ ] Albums
- [ ] Slider
- [ ] Lightbox Slideshow
- [ ] Password Protect
- [ ] Watermark
- [ ] Deeplink
- [ ] Right-Click Protection
- [ ] Advanced Shortcode
- [ ] SpeedUp
- [ ] Video

* Which browser is affected (or browsers): 
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other 

* Which device is affected (or devices): 
- [ ] Desktop
- [ ] Tablet
- [ ] Mobile
- [ ] Other 

#### Used versions
* WordPress version: 5.8
* Modula Lite version: 2.5.3
* Modula PRO version: 2.5.3
* Albums version: -
* Slider version: -
* Lightbox Slideshow version: -
* Password Protect version: -
* Watermark version: -
* Deeplink version: -
* Right-Click Protection version: -
* Advanced Shortcode version: -
* SpeedUp version: -
* Video version: -

**Comment by razvanaldea89** [comment]
Gives critical error if PHP extension `fileinfo` is not installed. Should check if exists and if not the mime type needs to be retrieved from somewhere else.
