### ISSUE TITLE
Incompatibility between gutenberg block and widgets

### ISSUE THREAD

**Issue by andyluak** [WPChill/modula-lite#599]
**Describe the bug**
Go to appeareance -> widgets and add gutenberg block . 

**To Reproduce**

**Expected behavior**

**Screenshots**

* Which addons do you have installed: 
- [ ] Modula PRO
- [ ] Albums
- [ ] Slider
- [ ] Lightbox Slideshow
- [ ] Password Protect
- [ ] Watermark
- [ ] Deeplink
- [ ] Right-Click Protection
- [ ] Advanced Shortcode
- [ ] SpeedUp
- [ ] Video

* Which browser is affected (or browsers): 
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other 

* Which device is affected (or devices): 
- [ ] Desktop
- [ ] Tablet
- [ ] Mobile
- [ ] Other 

#### Used versions
* WordPress version: 
* Modula Lite version: 
* Modula PRO version: -
* Albums version: -
* Slider version: -
* Lightbox Slideshow version: -
* Password Protect version: -
* Watermark version: -
* Deeplink version: -
* Right-Click Protection version: -
* Advanced Shortcode version: -
* SpeedUp version: -
* Video version: -

**Comment by razvanaldea89** [comment]
Not OK yet. The main problem here is that `wp-editor` is enqueued, and it should not be enqueued together with the new widgets editor.

![image](https://user-images.githubusercontent.com/44024114/133726557-d0341d9f-8101-46d8-892b-d5196433e555.png)

**Comment by razvanaldea89** [comment]
@TeoAlex think you did something similar to the PRO version of the plugin.

**Comment by TeoAlex** [comment]
Tested and the issue was fixed in a previous update.
