### ISSUE TITLE
width default to 100%

### ISSUE THREAD

**Issue by giucu91** [WPChill/modula-lite#601]
**Describe the bug**
If there is no value fort width we will put 100%.

https://tppr.me/dakfU
https://tppr.me/V9U10

**To Reproduce**

**Expected behavior**

**Screenshots**

* Which addons do you have installed: 
- [ ] Modula PRO
- [ ] Albums
- [ ] Slider
- [ ] Lightbox Slideshow
- [ ] Password Protect
- [ ] Watermark
- [ ] Deeplink
- [ ] Right-Click Protection
- [ ] Advanced Shortcode
- [ ] SpeedUp
- [ ] Video

* Which browser is affected (or browsers): 
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other 

* Which device is affected (or devices): 
- [ ] Desktop
- [ ] Tablet
- [ ] Mobile
- [ ] Other 

#### Used versions
* WordPress version: 
* Modula Lite version: 
* Modula PRO version: -
* Albums version: -
* Slider version: -
* Lightbox Slideshow version: -
* Password Protect version: -
* Watermark version: -
* Deeplink version: -
* Right-Click Protection version: -
* Advanced Shortcode version: -
* SpeedUp version: -
* Video version: -

**Comment by razvanaldea89** [comment]
We should go with `min-width : 100%` in order for the Gutenberg blocks to fully work in themes like 2022 ( think the Full Site Editing is affecting this ). For example, setting the  with to `100%`  and giving the block Full width setting ( see screenshot below ) will force the gallery not to be 100%.

![image](https://user-images.githubusercontent.com/44024114/154983737-ab3fc383-46f7-4002-9eb1-e8e8fd9870a0.png)

![image](https://user-images.githubusercontent.com/44024114/154983604-a5db68d2-0ea3-47e9-870a-b9d79fa0d17b.png)
