### ISSUE TITLE
border pixel showing before the gallery loads

### ISSUE THREAD

**Issue by mplusb** [WPChill/modula-lite#605]
**Describe the bug**
if you add a border and a border radius, before the gallery fully loads you will see a white dot on the left corner of the gallery

**To Reproduce**
1. Go to a gallery > edit it > add 1 border and 5 border radius > save the gallery
2. add it on a page with a black background to see it better
3. refresh the page to see it
screenshot:  
<img width="1322" alt="Screenshot 2021-09-27 at 13 22 45" src="https://user-images.githubusercontent.com/26008574/134891166-8d4d5a8b-6063-4e88-90d9-0e0cce864466.png">

* Which addons do you have installed: 
- [ ] Modula PRO
- [ ] Albums
- [ ] Slider
- [ ] Lightbox Slideshow
- [ ] Password Protect
- [ ] Watermark
- [ ] Deeplink
- [ ] Right-Click Protection
- [ ] Advanced Shortcode
- [ ] SpeedUp
- [ ] Video

* Which browser is affected (or browsers): 
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other 

* Which device is affected (or devices): 
- [ ] Desktop
- [ ] Tablet
- [ ] Mobile
- [ ] Other 

#### Used versions
* WordPress version: 5.8.1
* Modula Lite version: 2.5.4
* Modula PRO version: -
* Albums version: -
* Slider version: -
* Lightbox Slideshow version: -
* Password Protect version: -
* Watermark version: -
* Deeplink version: -
* Right-Click Protection version: -
* Advanced Shortcode version: -
* SpeedUp version: -
* Video version: -

**Comment by TeoAlex** [comment]
Can not reproduce. Tested with the specified settings and could't identify a dot.
