### ISSUE TITLE
add signal

### ISSUE THREAD

**Issue by mplusb** [WPChill/modula-lite#615]
**Is your feature request related to a problem? Please describe.**
 is it possible to integrate SIGNAL beside WhatsApp to the share button in the Lightbox?

**Describe the solution you'd like**
include signal as an whatsapp alternative

**Describe alternatives you've considered**

**Additional context**
https://secure.helpscout.net/conversation/1655518948/41531?folderId=1289779

**Comment by giucu91** [comment]
No.
