### ISSUE TITLE
add lightbox for all images

### ISSUE THREAD

**Issue by mplusb** [WPChill/modula-lite#619]
**Is your feature request related to a problem? Please describe.**
Do you guys know what’s the problem with all your plugins? They are not made for WP, but they don’t work fine with it. You have cool galleries, but for some reason you think that everyone will upload only to them. And what to do if WP images are used in parallel. If your Lightbox works, then the rest of the images that are outside the galleries are sent to the new window. And if you put an additional plugin for WP, then the image will open in two Lightboxes.

**Additional context**
https://wordpress.org/support/topic/problem-with-lightbox-14/

**Comment by giucu91** [comment]
there are 2 lightbox plugins that works with modula.
