### ISSUE TITLE
Gallery not working in tabs / accordion items

### ISSUE THREAD

**Issue by andyluak** [WPChill/modula-lite#620]
**Describe the bug**
Add modula inside a tab 
Modula will fail to render 

**To Reproduce**

**Expected behavior**

**Screenshots**

* Which addons do you have installed: 
- [ ] Modula PRO
- [ ] Albums
- [ ] Slider
- [ ] Lightbox Slideshow
- [ ] Password Protect
- [ ] Watermark
- [ ] Deeplink
- [ ] Right-Click Protection
- [ ] Advanced Shortcode
- [ ] SpeedUp
- [ ] Video

* Which browser is affected (or browsers): 
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other 

* Which device is affected (or devices): 
- [ ] Desktop
- [ ] Tablet
- [ ] Mobile
- [ ] Other 

#### Used versions
* WordPress version: 
* Modula Lite version: 
* Modula PRO version: -
* Albums version: -
* Slider version: -
* Lightbox Slideshow version: -
* Password Protect version: -
* Watermark version: -
* Deeplink version: -
* Right-Click Protection version: -
* Advanced Shortcode version: -
* SpeedUp version: -
* Video version: -

**Comment by beatricelucaci** [comment]
We need to test this with this: https://wordpress.org/plugins/responsive-tabs/
"I have ‘Responsive Tabs’ on the Performances page and although I can see the ‘Edit Gallery’ link showing me that the gallery is in fact there, it’s just not displaying any images." 
https://wordpress.org/support/topic/galleries-not-displaying-within-shortcode-2/

**Comment by TeoAlex** [comment]
Tested with https://wordpress.org/plugins/responsive-tabs/ and 2 other top wp.org tabs plugins and it works

https://user-images.githubusercontent.com/19348508/153172775-624465dd-fd37-46ba-ba7a-c7490a2695f3.mp4

.
