### ISSUE TITLE
conflict between Modula and Custom Post Type UI

### ISSUE THREAD

**Issue by beatricelucaci** [WPChill/modula-lite#626]
**Describe the bug**
 I am able to create a gallery and insert it into the default WordPress page and post types, but I receive and error when attempting to add a gallery to custom post types. I insert the Modula Gallery block and when I click on the "Display and existing gallery" option, I get the following error, "This block has encountered and error and cannot be previewed." 

https://secure.helpscout.net/conversation/1772852117/44130?folderId=4656050

**To Reproduce**
1. Go to 'CPT UI'
2. Create a post 
3. Edit the post
4. Insert the Modula gallery block 
5. See error

**Screenshots**
![Screenshot 2022-02-01 113207](https://user-images.githubusercontent.com/84579642/151944091-b6f90855-7fe9-433d-818d-41dc2deefe35.png)

* Which browser is affected (or browsers): 
- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other 

* Which device is affected (or devices): 
- [x] Desktop
- [ ] Tablet
- [ ] Mobile
- [ ] Other 

#### Used versions
* WordPress version: 5.9
* Modula Lite version: 2.5.5
* Custom Post Type UI: 1.10.2

**Comment by mplusb** [comment]
**you cannot use Modula's block in CPT**
https://secure.helpscout.net/conversation/1810833923/45200?folderId=1289779


I try to get the modula gutenberg block to work in a custom post type (CPT's).
PHP8.0 / Wordpress 5.9.1 / Generatepress premium / Modula Pro.

PHP Settings of my CPT:

function post_type_projecten()
{
$args = array(
'labels' => array(
'name' => 'Projecten',
'singular_name' => 'Project',
'add_new' => 'Nieuwe toevoegen',
'add_new_item' => 'Voeg nieuw project toe',
'all_items' => 'Alle projecten',

),
'hierarchical' => true,
'public' => true,
'has_archive' => true,
'menu_icon' => 'dashicons-smiley',
'supports' => array('title','editor'),
'show_in_rest' => true,
);

register_post_type('projecten',$args);
}
add_action('init', 'post_type_projecten');

//**-------------Custom post type taxonomy-----------**//

function projecten_taxonomy()
{
$args = array(

'labels' => array(
'name' => 'Project categorieën',
'singular_name' => 'Project categorie',
),

'public' => true,
'hierarchical' => true,
);

register_taxonomy('Project categorieën', array('projecten'), $args);
}
add_action('init', 'projecten_taxonomy');?>

Message:

- Gutenberg is enabled at CPT's. and works as expected with native gutenberg blocks.
- The modula gallery block works fine with normal posts and normal pages.
- The block is visible within Custom post types but when I select this block it is not possible to select a gallery. I get the message: "there has been an error and the preview cannot be shown. I read somewhere about a modula widget but it's only visible in the sidebar not in CPT.

Please help me

**Comment by razvanaldea89** [comment]
Made a proper check to ensure the files needed for the Gutenberg Editor are enqueued only in the present of the Gutenberg Editor
