### ISSUE TITLE
React warning in gutenberg block

### ISSUE THREAD

**Issue by TeoAlex** [WPChill/modula-lite#628]
**Describe the bug**
Adding/editing a Modula Gallery block in gutenberg editor throws multiple wrnings:

Warning: Each child in a list should have a unique "key" prop. See https://reactjs.org/link/warning-keys ...
Warning: Invalid DOM property `class`. Did you mean `className`?
Warning: Invalid DOM property `fill-rule`. Did you mean `fillRule`?
**To Reproduce**
1. Create a gallery,
2. Create a new page/post.
3. Open console and add a Modula gutenberg block.

![image](https://user-images.githubusercontent.com/19348508/153211227-d7244217-6f41-4b1b-8a07-e5a2dedb4e64.png)

**Comment by andyluak** [comment]
#626 - fixed here
