### ISSUE TITLE
Re-organize the menu entries

### ISSUE THREAD

**Issue by cristianraiber** [WPChill/modula-lite#633]
![image](https://user-images.githubusercontent.com/7841556/155282105-51e70345-45d0-4ae3-8337-36bb71d3406c.png)

**Comment by cristianraiber** [comment]
What's new:

- Welcome page (uses tabs)
-- Lite VS PRO goes here
-- Recommended Actions will go here (see Allegiant theme on W.org)
- re-name Gallery Defaults & Albums Defaults to just "Defaults"
- indent and add the right arrow icon

Move 
- Migrate -> Settings area
- Import/Export -> Settings area

Remove
- Lite vs PRO sub-menu entry
- Extensions sub-menu entry

**Comment by giucu91** [comment]
@cristianraiber mai vrei sa facem asta ?

1. nu putem punem sub menu la sub menu, adica partea cu welcome menu.
2. Vrei sa mai mutam migrate si import/export ?
3. Vrei sa scoatem din menu lite vs pro si sa o mutam in getting started page ?

**Comment by cristianraiber** [comment]
@giucu91 - 

1. cred c-am discutat despre asta si s-a hotarat ca se poate 
2. da
3. da

**Comment by TeoAlex** [comment]
A change was made here aswell to reflect the update: https://github.com/WPChill/modula-defaults/issues/51 & here https://github.com/WPChill/modula-pro/issues/565
