### ISSUE TITLE
hide the URL display link in bottom left corner in browser

### ISSUE THREAD

**Issue by mplusb** [WPChill/modula-lite#635]
**Is your feature request related to a problem? Please describe.**
hide the URL display link in bottom left corner when hovering on one of the photos in the gallery

<img width="797" alt="Screenshot 2022-02-23 at 13 01 01" src="https://user-images.githubusercontent.com/26008574/155306727-a40b524c-799a-4e3d-afef-c48fb231a9af.png">

**Describe the solution you'd like**
https://stackoverflow.com/questions/30410748/how-to-hide-link-information-at-the-bottom-left-right-of-the-browser-on-hover

**Additional context**
https://secure.helpscout.net/conversation/1789327342/44614?folderId=1289779

**Comment by cristianraiber** [comment]
This is not possible. That's a browser feature.
