### ISSUE TITLE
experiencing fatal error on mobile devices

### ISSUE THREAD

**Issue by beatricelucaci** [WPChill/modula-lite#636]
**Describe the bug**
I have three modula galleries on my website and they all have all started to have the same problem very recently. There is a space for the gallery, but the pictures inside are not showing. In addition to the URL above the problem occurs on:
https://www.loggosretreat.co.uk/paxos/
https://www.loggosretreat.co.uk/testimonials/

I tried to use the advice in response to an earlier query to amend the modula-helper-functions.php but not having much experience in code I have now messed up all three pages and they are not loading at all.

I should add that I am using a Firefox browser on my mobile 

On two occasions, including when I first opened the test gallery Mihaela sent me, the images were there for a split second and then disappeared.
I have been looking into this further and I think it is a Firefox issue.

The galleries are not showing in Firefox on my mobile or PC, but they are showing on Chrome and Edge (on the PC) and on Samsung internet on a mobile device.

https://wordpress.org/support/topic/also-experiencing-fatal-error-on-mobile-devices/

* Which browser is affected (or browsers): 
- [ ] Chrome
- [x] Firefox
- [ ] Safari
- [ ] Other 

* Which device is affected (or devices): 
- [ ] Desktop
- [ ] Tablet
- [x] Mobile
- [ ] Other

**Comment by mplusb** [comment]
it appears galleries are missing on mobile on iPhone 6S as well: https://wordpress.org/support/topic/galleries-have-dissappeared-on-mobile/

**Comment by cristianraiber** [comment]
MacOS, Xcode - iPhone Simulator - simulate iPhone 6S

**Comment by cristianraiber** [comment]
![Uploading AB170085-232F-4E96-BB90-4F03852CFDD5.jpeg…]()

**Comment by cristianraiber** [comment]
![AB170085-232F-4E96-BB90-4F03852CFDD5](https://user-images.githubusercontent.com/7841556/156221142-11d4bb78-891f-4abd-b231-9963cc406544.jpeg)

**Comment by cristianraiber** [comment]
Tested using iPhone 7+

**Comment by beatricelucaci** [comment]
Do you have any news? The user is asking

**Comment by beatricelucaci** [comment]
I use the Modula Gallery on the website https://seegut-blaueblume.de/.
Unfortunately the galleries are not displayed on Safari Version 12.1.2 (12607.3.10)
I use a Macbook pro with Version 12.1.2 (12607.3.10) with MacOS 10.12.6
In Firefox and chrome everything works fine.

https://secure.helpscout.net/conversation/1822373030/45565/

**Comment by cristianraiber** [comment]
@beatricelucaci 

![CleanShot 2022-03-22 at 11 54 34@2x](https://user-images.githubusercontent.com/7841556/159476284-ecc6600f-65ed-46d1-bfb3-3df7285b8f90.jpg)

**Comment by cristianraiber** [comment]
![CleanShot 2022-03-22 at 11 55 06@2x](https://user-images.githubusercontent.com/7841556/159476364-f97d5887-51d5-48c0-bd88-b442aea98505.jpg)

**Comment by cristianraiber** [comment]
![CleanShot 2022-03-22 at 11 55 34@2x](https://user-images.githubusercontent.com/7841556/159476456-119eeee5-3bb6-46ed-9d4f-c622a6b79543.jpg)

**Comment by TeoAlex** [comment]
Tested on Firefox Browser for Android v 98.2.0.
https://user-images.githubusercontent.com/19348508/159917280-d72d7312-a75f-459e-ac9e-ff5a616ddf10.mp4

![Screenshot_2022-03-24-14-33-52-372](https://user-images.githubusercontent.com/19348508/159917295-2292440f-2fe4-4f83-b455-782565be4850.png)

**Comment by razvanaldea89** [comment]
Firefox v98.0.2 - 64-bit

![image](https://user-images.githubusercontent.com/44024114/159917333-0c535c00-83a6-413a-a309-7a4b12ff2bc6.png)

Firefox 98.2.0 on mobile

![Screenshot_2022-03-24-14-35-44-552_org mozilla firefox](https://user-images.githubusercontent.com/44024114/159917727-c4708df9-6d81-4631-b0f7-da8cff18adf4.jpg)
