### ISSUE TITLE
arrows from metaboxes do not work when you edit a gallery

### ISSUE THREAD

**Issue by mplusb** [WPChill/modula-lite#639]
**Describe the bug**
arrows from metaboxes do not work when you edit a gallery

**To Reproduce**
1. Go to a gallery > edit it > metaboxes have up and down arrows to move the boxes around
2. Click on them > it does not work

**Screenshots**
<img width="1260" alt="Screenshot 2022-03-04 at 16 11 27" src="https://user-images.githubusercontent.com/26008574/156778555-0ae678f5-1a1e-4418-9dc9-a0cc15ac16d1.png">

* Which browser is affected (or browsers): 
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other 

* Which device is affected (or devices): 
- [ ] Desktop
- [ ] Tablet
- [ ] Mobile
- [ ] Other 

#### Used versions
* WordPress version: 5.9.1
* Modula Lite version: 2.6.2
* Modula PRO version: -
* Albums version: -
* Slider version: -
* Lightbox Slideshow version: -
* Password Protect version: -
* Watermark version: -
* Deeplink version: -
* Right-Click Protection version: -
* Advanced Shortcode version: -
* SpeedUp version: -
* Video version: -

**Comment by razvanaldea89** [comment]
Metaboxes will be forever opened. Arrows won't work, the setup will remain the same as the initial one because many users complained that they moved the metaboxes from left to right or the other way around and could not move them back.
Also, the arrows will now be hidden.
