### ISSUE TITLE
improve fancybox script

### ISSUE THREAD

**Issue by mplusb** [WPChill/modula-lite#661]
**Is your feature request related to a problem? Please describe.**
when you click an image and it opens the lightbox, it shuffles the gallery. Then, when closing the image, it shuffles again. happens only on Windows + Chrome

seems to be related to:
third party JavaScript, which adds that margin (17px) in order to mimic right side scroll bar
problematic for users who have full-width websites. You may wish to confer with the creator of the script you are using just to ensure. It doesn't just affect the lightbox, but it also affects the *entire website* when the lightbox is opened on Chrome for Windows.

Consulting with a good coding friend, he believes that this "fix" to mimic the scroll bar is no longer necessary as it tries to fix a problem that doesn't generally exist anymore in modern browsers.

**Additional context**
https://secure.helpscout.net/conversation/1892084976/47008?folderId=1289779

**Comment by itsthex** [comment]
Thanks for this guys!

**Comment by razvanaldea89** [comment]
Already launched
