### ISSUE TITLE
Modula + Elementor (Page Transitions = Enabled) + any other type of Themes = NOT working.

### ISSUE THREAD

**Issue by beatricelucaci** [WPChill/modula-lite#666]
**Describe the bug**
Hi, I have an issue between the "Modula", "Elementor Pro" and "Hello theme". If I enable the Elementor option in: Elementor + Settings + Experiments + Page Transitions = Active or Default. The Modula plugin "FREEZE". The preview of the images is blocked and no other images can be selected
I am using Elementor Pro + any other type of themes, I prefer the Hello
theme. For Elementor, Hello theme and Modula to work properly, I need to
DISABLE Elementor option "Page Transitions".
https://secure.helpscout.net/conversation/1924972530/47777?folderId=4656050

**Comment by TeoAlex** [comment]
Tested and the issue could not be reproduced.
