### ISSUE TITLE
full image card on Twitter 

### ISSUE THREAD

**Issue by beatricelucaci** [WPChill/modula-lite#672]
**Is your feature request related to a problem? Please describe.**
 I am using the free Modula version which is rather good however I have an issue with social sharing images to Twitter. When I share an image from a gallery to Twitter the image card does not display only a text format. The Facebook sharing options works perfectly and shows a full image card. 

https://secure.helpscout.net/conversation/1954509794/48447?folderId=4656050

![image](https://user-images.githubusercontent.com/84579642/180146262-1ec112d6-d235-4552-ac8c-98b2bf1a6c9c.png)

**Comment by beatricelucaci** [comment]
any news? the user is asking

**Comment by beatricelucaci** [comment]
+1 https://support.wpchill.com/conversation/14573?folder_id=81

**Comment by cristeacosmin** [comment]
continue discussion on #945
