### ISSUE TITLE
error when placing any gallery

### ISSUE THREAD

**Issue by beatricelucaci** [WPChill/modula-lite#683]
**Describe the bug**
I get this error when placing any gallery : Warning :Trying to access array offset on value of type bool in: C:\xampp\htdocs\wcibertec\wp-content\plugins\modula-best-grid-gallery\includes\public\modula-helper-functions.php on line 334 Is there a solution?

https://secure.helpscout.net/conversation/2013360603/49880?folderId=4656050

**Comment by TeoAlex** [comment]
the mentioned error was fixed in a previous commit and released in v2.6.8
