### ISSUE TITLE
remove 'open image in lightbox' when you hover over an image in the gallery

### ISSUE THREAD

**Issue by mplusb** [WPChill/modula-lite#686]
to disable this:
<img width="956" alt="Screenshot 2022-09-26 at 14 40 36" src="https://user-images.githubusercontent.com/26008574/192267463-e9cb643a-e053-4d3f-86c1-ad424a6b3c09.png">

**Comment by cristianraiber** [comment]
![image](https://user-images.githubusercontent.com/7841556/192272866-8e72d966-f219-4361-9fad-0f9d08c3c2e1.png)

**Comment by cristianraiber** [comment]
title should be removed
