### ISSUE TITLE
Lazy load not working properly

### ISSUE THREAD

**Issue by TeoAlex** [WPChill/modula-lite#688]
It seems like Lazy Load for Modula doesn't work properly as [PageSpeed Insights](https://pagespeed.web.dev/) returns a low score.
https://github.com/aFarkas/lazysizes - the library we use for lazy load

**Comment by mplusb** [comment]
+1 

To explain the problem again, inside the chrome developers tools - network tab - and the view is switched to the mobile view while Disable cache is turned on, the waterfall shows that all 124 images are loaded immediately upon page load (all with a status of 200 and in AVIF format). Then, when scrolling, all images are loaded again "correctly" as lazy-load. So all images are loaded the first time the page loads and then again when scrolling.
