### ISSUE TITLE
Accordeons weird behaviour

### ISSUE THREAD

**Issue by cristianraiber** [WPChill/modula-lite#690]
Video: https://www.loom.com/share/ebc096b41d904ddb9d5fb626351c61d0

- Expand accordion
- Toggle parent to ON 
- Toggle parent to OFF
- accordion collapses, even though I didn't click on it

**Comment by giucu91** [comment]
@TeoAlex pare ca child pe setare e pusa gresit

**Comment by cristianraiber** [comment]
Also re-organise the settings so they'll be in order.

![image](https://user-images.githubusercontent.com/7841556/196409455-92973db5-ce36-420a-a2df-fe5604abbc8f.png)


Toggling the "Share Button" to ON enables the settings that make it look like they're children of Download Button.
