### ISSUE TITLE
image sizes displaying strangely 

### ISSUE THREAD

**Issue by beatricelucaci** [WPChill/modula-lite#692]
**Describe the bug**
After Update to V 2.6.8 the 'Image size' section displays a lot of numbers 
https://secure.helpscout.net/conversation/2041303053/0/?folderId=4656050

this is what the user have 
![image](https://user-images.githubusercontent.com/84579642/196618834-c6c8b1ca-fe3a-452d-be74-a8e95724bc3d.png)

this is what I see 
![image](https://user-images.githubusercontent.com/84579642/196619088-5eff4f5a-3c72-428b-8110-5d209011270d.png)

* Which browser is affected (or browsers): 
- [x] Chrome

* Which device is affected (or devices): 
- [x] Desktop

#### Used versions
* WordPress version: 6.0.3
* Modula Lite version: 2.6.9

**Comment by mplusb** [comment]
+1
