### ISSUE TITLE
 Migration from wp core galleries not working 

### ISSUE THREAD

**Issue by mplusb** [WPChill/modula-lite#694]
**Describe the bug**
 Migration from wp core galleries not working  - it shows as if they are imported, but no galleries display in modula galleries.

https://wordpress.org/support/topic/migration-not-working-5/

**To Reproduce**
1. create a wp gallery
2. migrate it
3. See error

#### Used versions
* WordPress version: 6.0.2
* Modula Lite version: 2.6.91
* Modula PRO version: -
* Albums version: -
* Slider version: -
* Lightbox Slideshow version: -
* Password Protect version: -
* Watermark version: -
* Deeplink version: -
* Right-Click Protection version: -
* Advanced Shortcode version: -
* SpeedUp version: -
* Video version: -

**Comment by beatricelucaci** [comment]
+1 https://secure.helpscout.net/conversation/2059764369/51402?folderId=4656050
