### ISSUE TITLE
screen options do not work in modula gallery

### ISSUE THREAD

**Issue by mplusb** [WPChill/modula-lite#700]
**Describe the bug**
when you edit a gallery > go to screen options > and turn on/off screen elements > nothing happens
<img width="1163" alt="Screenshot 2022-11-02 at 10 02 48" src="https://user-images.githubusercontent.com/26008574/199433023-be4f3804-4954-446f-b681-86096db4a5df.png">

* Which addons do you have installed: 
- [ ] Modula PRO
- [ ] Albums
- [ ] Slider
- [ ] Lightbox Slideshow
- [ ] Password Protect
- [ ] Watermark
- [ ] Deeplink
- [ ] Right-Click Protection
- [ ] Advanced Shortcode
- [ ] SpeedUp
- [ ] Video

* Which browser is affected (or browsers): 
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other 

* Which device is affected (or devices): 
- [ ] Desktop
- [ ] Tablet
- [ ] Mobile
- [ ] Other 

#### Used versions
* WordPress version: 6.0.3
* Modula Lite version: 2.6.92
* Modula PRO version: 2.6.1

**Comment by beatricelucaci** [comment]
+1 https://secure.helpscout.net/conversation/2055534853/51247?folderId=4656050

**Comment by razvanaldea89** [comment]
https://github.com/WPChill/modula-lite/commit/fd238edd4b6a8680f01dfe2e924e1adba9f3420c this commit fixed this also
