### ISSUE TITLE
adding <a href> to the caption/title - breaks lightbox

### ISSUE THREAD

**Issue by mplusb** [WPChill/modula-lite#707]
**Describe the bug**
 On your page you write that "How to add HTML to your caption/title You can add HTML for your image title or caption. This will be displayed inside the lightbox under the image, or on hover. You will have to go to your gallery > edit it > then edit the desired image > and inside the title or caption fields > add the HTML code. If you want to add a link, you can use for example: <a href="enter your url here">Click HERE for more information</a>" https://wp-modula.com/kb/modula-caption-configuration/ that it is also possible to insert html code with a link to the URL in the image caption, but if I do so, the thumbnail doesn't even appear in the lightbox, the black box remains and the whole lightbox is buggy. The html code in the image caption affects the lightbox code and inserts another </a> there, breaking the url. You show an example at https://wp-modula.com/kb/modula-caption-configuration/, but it doesn't work in practice.

**To Reproduce**
1. Go to an image in the gallery > enter <a> tag in the caption
2. open lightbox
3. See error

**Expected behavior**
should add a link in the caption - worked before

**Screenshots**

* Which addons do you have installed: 
- [ ] Modula PRO
- [ ] Albums
- [ ] Slider
- [ ] Lightbox Slideshow
- [ ] Password Protect
- [ ] Watermark
- [ ] Deeplink
- [ ] Right-Click Protection
- [ ] Advanced Shortcode
- [ ] SpeedUp
- [ ] Video

* Which browser is affected (or browsers): 
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other 

* Which device is affected (or devices): 
- [ ] Desktop
- [ ] Tablet
- [ ] Mobile
- [ ] Other 

#### Used versions
* WordPress version: 6.1.1
* Modula Lite version: 2.6.92
* Modula PRO version: 2.6.1

**Comment by mplusb** [comment]
appears to be working ok with versions 2.7.7 and 2.6.5

**Comment by TeoAlex** [comment]
Yes, it seems like the issue was fixed in a previous update.
