### ISSUE TITLE
ADA Compliance

### ISSUE THREAD

**Issue by TeoAlex** [WPChill/modula-lite#708]
"I have a site that is using your plugin for an image gallery, and when running an ADA compliance test over the site, it reports that one of the HTML attributes is not leaving a space after itself. Looking at the source, we can confirm that the images are being generated with HTML as follows: <img class="pic wp-image-1437" data-valign="middle" data-halign="center" alt="..." data-full="..." title="..." width="168" height="168" src="..." data-src="..." data-caption=""srcset="..." sizes="(max-width: 168px) 100vw, 168px"" /> Instances of "..." indicate content that is filled but not relevant. Note that the data-caption attribute doesn't have a space between it and srcset, and sizes ends with duplicate double quotes. "

https://secure.helpscout.net/conversation/2075572381/51960/

**Comment by mplusb** [comment]
settings in ticket @TeoAlex

**Comment by mplusb** [comment]
file includes/public/modula-helper-functions - lines: 423 added the space before srcset, line 426 removed the extra quote character from ' sizes="%s""'

**Comment by cristinnaiulia** [comment]
I ran ADA compliances tests over the site and there were no errors on modula pluglins. 
I used https://accessibe.com/accessscan and Web Accessibility Basic plugin for tests.

[662a1ec07038ee000394443f.pdf](https://github.com/WPChill/modula-lite/files/15107353/662a1ec07038ee000394443f.pdf)
