### ISSUE TITLE
Gallery type icons coloring

### ISSUE THREAD

**Issue by razvanaldea89** [WPChill/modula-lite#713]

**Comment by razvanaldea89** [comment]
When license active and option/extension contained in the license the icon should be gray with an install badge ( so not pro )

![image](https://user-images.githubusercontent.com/44024114/216296539-ce914555-d380-4945-92cd-8a2dde05532a.png)

**Comment by TeoAlex** [comment]
https://github.com/WPChill/modula-lite/issues/774
