### ISSUE TITLE
hide image from lightbox doesn't work

### ISSUE THREAD

**Issue by beatricelucaci** [WPChill/modula-lite#714]
**Describe the bug**
I just posted a new gallery and I followed the instructions on how to add white space by adding white images. I toggled on the "hide image from Lightbox" on every white image and I toggled off the "show all images" button in the Lightbox and links settings. It is not working, white images do appear in the Lightbox and they open if I click on them. Here's the gallery: https://www.irenekung.com/rough-tough-and-mystic/

https://secure.helpscout.net/conversation/2082093549/52255?folderId=4656050

**To Reproduce**
1. Go to Modula > Edit your gallery > add white images 
2. Click on the pencil icon on one of the white images to edit it > check the 'Hide image from lightbox' option? 
3. Add the gallery on a page > open  images in lightbox 
4. See error (the white images are displayed)

#### Used versions
* WordPress version: 6.1.1
* Modula Lite version: 2.7.0

**Comment by TeoAlex** [comment]
The issue where the "Hide from Lightbox" images were open on click was fixed here https://github.com/WPChill/modula-lite/commit/10504689bb256deee30fe84d00cf114a49a497bf
The issue where the "Hide from Lightbox" images were still shown in lightbox was related to Modula PRO and was fixed comming v2.6.3
