### ISSUE TITLE
 error messages displayed on the web page with the album embedded

### ISSUE THREAD

**Issue by beatricelucaci** [WPChill/modula-lite#775]
**Describe the bug**
I get a lot of error messages displayed on the web page with the album embedded: Warning: Undefined array key 5 in wp-content/plugins/modula-best-grid-gallery/includes/class-modula-script-manager.php on line 119 

https://secure.helpscout.net/conversation/2154711873/54406?folderId=4656050

**Comment by razvanaldea89** [comment]
Has commit 888876d
