### ISSUE TITLE
last row alignment when you set number of columns 

### ISSUE THREAD

**Issue by beatricelucaci** [WPChill/modula-lite#781]
**Is your feature request related to a problem? Please describe.**
Unfortunately when Masonry is selected as the Gallery type, and the columns are set to a specific value, the Last Row Alignment setting is disabled. I have posted a pic showing the settings here: https://media.altimac.com/images/modula-gallery.png
https://wordpress.org/support/topic/filling-browser-viewport-with-5-images/

**Comment by giucu91** [comment]
Last row is working only with Automatic columns
