### ISSUE TITLE
 Gallery Image Links to attachment page

### ISSUE THREAD

**Issue by mplusb** [WPChill/modula-lite#786]
**Is your feature request related to a problem? Please describe.**
Hello Support-Team,
I’ve created a gallery where images don’t open in a lightbox but refer to an URL. That works without any problem.
I use a hover effect which shows only the description, this works fine, too.
The only issue is: when hovering over an image you will also see a kind of tool-tip “Open attachment page”.
This is not the case when hovering over images in galleries which open in a lightbox.
I am working on an artist’s website where this hint “Open attachment page” on every image the user selects is annoying.
Is there any possibility to supress the hint?
I tried by myself, but couldn’t find a solution.
Thanks in advance for your help!

https://wordpress.org/support/topic/gallery-image-links-to-attachment-page/

**Comment by mplusb** [comment]
related to: https://github.com/WPChill/modula-lite/issues/686

**Comment by beatricelucaci** [comment]
+1 https://secure.helpscout.net/conversation/2235255980/56899/

**Comment by giucu91** [comment]
@TeoAlex add on the url title the title of the image
