### ISSUE TITLE
Getting Started Page

### ISSUE THREAD

**Issue by giucu91** [WPChill/modula-lite#800]
1. Cream un nou meniu -> Dashboard ( fix sub Modula menu, adica in loc de galleries ).
2. CSS-ul sa fie intr-un fisier separat, dar culorile butoanelor sa fie in pagina intre tagurile <style> deoarece acestea vor fi modificate in functie de ce plugin punem clasa.
3. Sa fie ca in design-ul atasat.
4. Scoatem pagina : wp-admin/edit.php?post_type=modula-gallery&page=modula-about-page si la fiecare update/instalare utilizatorul sa fie redirectionat pe aceasta pagina.
5. Din header mom nu o sa avem partea de my account si search.
6. Tabul Getting Started
     - va fi ca in poza
     - Common use cases vor fi preluate de pe wp-modula.com ca sa le putem modifica mereu.
     - view changelog o sa fie un link de pe wp.org trunk unde o sa fie un fisier changelog.md

7. Tabul About US : 
    - va fi pagina de aici : https://wpchill.com/about/
    - pana la Our Story dupa Our values punem un buton find more about us si sa te duca pe pagina de la wpchill

8. Partners
   - va fi o lista cu parteneri, majoritatea o sa fie pluginuri de pe wp.org
   - acesti parteneri ii vom lua cu ajax de pe wp-modula.com si o sa ii pastram intr-un transient timp de 1 saptamana.
   - trebuie verifica ca daca linkul de install este de pe wp.org sa avem 1 click install ca la extensii.
   - ca design o sa folosim ce avem la extensii, doar ca o sa fie un button Install plugin, si daca pluginul este instalat o sa fie un button disabled pe care scrie Already installed.
   - daca linkul nu e de pe wp.org, atunci inseamna ca partenerul nu are pluginul pe wp.org si o sa fie un link catre site-ul pluginului si butonul o sa aibe labelul "Find more"

9. Extensions te va duce pe pagina de extensii
10. LITE vs PRO - >te va duce pe pagina de lite vs PRO, acest tab dispare daca avem o licenta activa.
![modula-getting-started](https://github.com/WPChill/modula-lite/assets/7580330/5a33922e-989e-4575-9e0b-d1816f408dae)

**Comment by cristianraiber** [comment]
- View full changelog ar putea sa duca catre changelog.txt din plugin, ca sa fie ușor 
- Vor fi si plugin-uri care nu au versiune pe w.org (cum ar fi LearnDash), deci ar trebui sa putem sa adaugam plugin-uri si din afara w.org-ului (logo, descriere, URL ale plugin-ului)

**Comment by TeoAlex** [comment]
O sa avem nevoie de imagini, iconuri, coduri de culoare si font data ( astea daca nu sunt, le nimeresc eu cumva )

**Comment by cristianraiber** [comment]
Ti le pot da eu pe toate. Mi-am pus reminder sa ma ocup maine dimineata

**Comment by cristianraiber** [comment]
- Codul de culoare (bej): #fef2ea
- Verdele de pe butoane: #33a370
- border-ul box-urilor: #D9D9D9
- font family: DM Sans (as merge totusi mai degraba pe font family-ul default din WP)
<img width="420" alt="background-box" src="https://github.com/WPChill/modula-lite/assets/7841556/52a49a96-1f5f-4739-965a-7729c8b681f0">
<img width="1772" alt="banner-upsell" src="https://github.com/WPChill/modula-lite/assets/7841556/b8a724c9-a2fa-4f56-8187-dc45a778c2ff">
<img width="136" alt="icons8-book-shelf-96" src="https://github.com/WPChill/modula-lite/assets/7841556/2ba377ab-1788-4173-bc8e-521054868ed1">
<img width="48" alt="icons8-changelog-48" src="https://github.com/WPChill/modula-lite/assets/7841556/a5f792f2-a524-4ef3-9ce8-c0d2ebcc0872">
<img width="105" alt="icons8-extensions-96" src="https://github.com/WPChill/modula-lite/assets/7841556/c86ffd98-f30f-4517-a51a-82f53ac49794">
<img width="113" alt="icons8-galleries-96" src="https://github.com/WPChill/modula-lite/assets/7841556/08f255ee-1071-41dd-83c6-0782aaff6d76">
<img width="48" alt="icons8-help-48" src="https://github.com/WPChill/modula-lite/assets/7841556/5aec73e2-94ef-41db-8d38-47453e6e3a84">
<img width="48" alt="icons8-lock-48" src="https://github.com/WPChill/modula-lite/assets/7841556/6cb2994d-fa95-4039-a971-620d5f4b3998">
<img width="109" alt="icons8-services-96" src="https://github.com/WPChill/modula-lite/assets/7841556/573e1b52-438a-4cb0-8aba-1bb44d9bfaa4">

atasate, si pozele

**Comment by giucu91** [comment]
<img width="1462" alt="image" src="https://github.com/WPChill/modula-lite/assets/7580330/3e3ad323-83ba-4780-9bec-3709d315674c">

- [ ] facut toata pagina alba
- [ ] margin stanga-dreapta ca pe prima pagina

**Comment by giucu91** [comment]
<img width="811" alt="image" src="https://github.com/WPChill/modula-lite/assets/7580330/5c865794-679c-4155-af7a-5606182402b7">

- [ ] pagina de lite vs pro nu merge

**Comment by giucu91** [comment]
<img width="358" alt="image" src="https://github.com/WPChill/modula-lite/assets/7580330/ed4b95c4-b1d8-4aef-9598-2f9cff6f671a">

- [ ] nu merge linkul de documentatie / vezi https://github.com/WPChill/modula-lite/issues/803

**Comment by razvanaldea89** [comment]
![image](https://github.com/WPChill/modula-lite/assets/44024114/9bd43958-4de3-4bb5-92e5-586f4a479592)
Trebuie scos Agency de acolo, nu mai exista pachetul
