### ISSUE TITLE
Show all / Show less button in admin edit gallery

### ISSUE THREAD

**Issue by TeoAlex** [WPChill/modula-lite#809]
Maby we should add a "Show all images" button in Gallery box ( Edit gallery page) and limit the number of images displayed to 24( 3 rows).

The prefference( Show all images/ Show less images ) should be saved in the gallery's settings.

**Comment by giucu91** [comment]
Why ? What problem resolve this issue ?

**Comment by razvanaldea89** [comment]
Think this will be solved with managing https://github.com/WPChill/modula-lite/issues/704 issue
