### ISSUE TITLE
specify width and height on custom dimensions

### ISSUE THREAD

**Issue by beatricelucaci** [WPChill/modula-lite#814]
**Is your feature request related to a problem? Please describe.**
When you go to your WP dashboard > Modula > edit your gallery > General settings > Image size: Custom > Image dimensions - it would be helpful to specify there which size is the width and which one is the height

**Comment by razvanaldea89** [comment]
@TeoAlex please add placeholders to these ones. If there is no "placeholder" option for the input type text please add one.
