### ISSUE TITLE
incompatibility with stackable

### ISSUE THREAD

**Issue by mplusb** [WPChill/modula-lite#834]
**Describe the bug**
If you are using this plugin: https://wordpress.org/plugins/stackable-ultimate-gutenberg-blocks/
and you use it to create tabs (it comes with a tab block) > in each tab you add a modula gallery > when you click on an image it will open in lightbox a random image from a different modula gallery that is another tab.

**To Reproduce**
see above

* Which addons do you have installed: 
- [ ] Modula PRO
- [ ] Albums
- [ ] Slider
- [ ] Lightbox Slideshow
- [ ] Password Protect
- [ ] Watermark
- [ ] Deeplink
- [ ] Right-Click Protection
- [ ] Advanced Shortcode
- [ ] SpeedUp
- [ ] Video

* Which browser is affected (or browsers): 
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other 

* Which device is affected (or devices): 
- [ ] Desktop
- [ ] Tablet
- [ ] Mobile
- [ ] Other 

#### Used versions
* WordPress version: 6.3
* Modula Lite version: 2.7.4
* Modula PRO version: 2.6.4
* Albums version: -
* Slider version: -
* Lightbox Slideshow version: -
* Password Protect version: -
* Watermark version: -
* Deeplink version: -
* Right-Click Protection version: -
* Advanced Shortcode version: -
* SpeedUp version: -
* Video version: -

**Comment by razvanaldea89** [comment]
Bug was fixed starting with Stackable version 3.11.0. Going to close this.
