### ISSUE TITLE
PHP Fatal error: Uncaught Error: Class 'Modula_Upgrades' not found

### ISSUE THREAD

**Issue by mplusb** [WPChill/modula-lite#835]
**Describe the bug**
throws a fatal error randomly (error from PHP error log in ticket)

Modula is causing various issues on my site. I am getting a regular WP email saying that there's a problem with my website. I have only identified that it's Modula by deactivating and testing several different plugins. Modula is the only one that causes the issues, which are quite random and unrelated. For example, the most recent issue caused me to not be able to save a new page. 

**To Reproduce**
was unable to replicate it

* Which addons do you have installed: 
- [ ] Modula PRO
- [ ] Albums
- [ ] Slider
- [ ] Lightbox Slideshow
- [ ] Password Protect
- [ ] Watermark
- [ ] Deeplink
- [ ] Right-Click Protection
- [ ] Advanced Shortcode
- [ ] SpeedUp
- [ ] Video

* Which browser is affected (or browsers): 
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other 

* Which device is affected (or devices): 
- [ ] Desktop
- [ ] Tablet
- [ ] Mobile
- [ ] Other 

#### Used versions
* WordPress version: 
* Modula Lite version: 2.7.4
* Modula PRO version: -
* Albums version: -
* Slider version: -
* Lightbox Slideshow version: -
* Password Protect version: -
* Watermark version: -
* Deeplink version: -
* Right-Click Protection version: -
* Advanced Shortcode version: -
* SpeedUp version: -
* Video version: -
https://secure.helpscout.net/conversation/2318960110/58784?folderId=1289779

**Comment by beatricelucaci** [comment]
+1 https://support.wpchill.com/conversation/4525?folder_id=81

**Comment by TeoAlex** [comment]
fixed here https://github.com/WPChill/modula-lite/commit/4e2a5e489d08b4afa96245606ffc3e9d76d07e02 and released in v 2.7.8
