### ISSUE TITLE
Image attribution gone wild when "none" is selected

### ISSUE THREAD

**Issue by razvanaldea89** [WPChill/modula-lite#840]
**Describe the bug**
When "none" is selected for the `Image Attribution` setting on the front something undesired is happening, it displays "false" everywhere in the `application/ld+json` context.

**Expected behavior**

**Screenshots**
![image](https://github.com/WPChill/modula-lite/assets/44024114/3ac88d0d-8da9-47c6-8269-d14cee1af103)
<img width="776" alt="image" src="https://github.com/WPChill/modula-lite/assets/44024114/ecb4434f-55bc-4e61-96cf-e726cea01004">

* Which addons do you have installed: 
- [ ] Modula PRO
- [ ] Albums
- [ ] Slider
- [ ] Lightbox Slideshow
- [ ] Password Protect
- [ ] Watermark
- [ ] Deeplink
- [ ] Right-Click Protection
- [ ] Advanced Shortcode
- [ ] SpeedUp
- [ ] Video

* Which browser is affected (or browsers): 
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other 

* Which device is affected (or devices): 
- [ ] Desktop
- [ ] Tablet
- [ ] Mobile
- [ ] Other 

#### Used versions
* WordPress version: 
* Modula Lite version: 
* Modula PRO version: -
* Albums version: -
* Slider version: -
* Lightbox Slideshow version: -
* Password Protect version: -
* Watermark version: -
* Deeplink version: -
* Right-Click Protection version: -
* Advanced Shortcode version: -
* SpeedUp version: -
* Video version: -

**Comment by aceArt-GmbH** [comment]
>need testing

We upgraded and it fixed the bug, thanks :heart:

**Comment by cristianraiber** [comment]
@aceArt-GmbH - stoked to hear that!
