### ISSUE TITLE
1-click install in Dashboard

### ISSUE THREAD

**Issue by cristianraiber** [WPChill/modula-lite#845]
- Yoast SEO & ShortPixel 1-click installation seems to need fixing. 

Even though the plugins are installed, the message on the screen says "Install." 

![image](https://github.com/WPChill/modula-lite/assets/7841556/72aa8f26-77b7-42c9-ae7d-ea83aca23cf6)
---
![image](https://github.com/WPChill/modula-lite/assets/7841556/38340555-c4cf-4aca-85f1-429ba566c027)

**Comment by giucu91** [comment]
@TeoAlex nu merge, pentru ca de exemplu pentru Yoast SEO slugul e wordpress-seo iar fisierul principal e wp-seo.php si noi cautam dupa wordpress-seo/wordpress-seo.php
