### ISSUE TITLE
New js&css enqueue method.

### ISSUE THREAD

**Issue by giucu91** [WPChill/modula-lite#846]
1. We need to change how we enqueue scripts in Modula. Since http/2 it is faster to enqueue more little scripts than one larger script. (https://speedboostr.com/concatenation-case-study/)

2. For debugging we will use the WP constant( SCRIPT_DEBUG ) to enqueue .min file like here : https://github.com/impress-org/givewp/blob/b6eaf5f0e1f66a977cc8418b20da64884d58ce4d/includes/admin/reports/class-give-graph.php#L154

3. We will delet all file from here : 
<img width="407" alt="image" src="https://github.com/WPChill/modula-lite/assets/7580330/d9eee16d-3bf5-487e-8f75-74d17c86e447">

4. We will delete these https://github.com/WPChill/modula-lite/blob/master/includes/class-modula-script-manager.php#L35, we  don't need anymore these script. 

5. All scripts from here https://github.com/WPChill/modula-lite/blob/master/includes/public/class-modula-shortcode.php#L39 and all css from here we will register all js files from here : https://github.com/WPChill/modula-lite/tree/master/assets/js/front and based on https://github.com/WPChill/modula-lite/blob/master/includes/class-modula-script-manager.php#L73 we will enqueue all the files necessary for modula and its addons

6. Rewirte https://github.com/WPChill/modula-lite/blob/master/includes/class-modula-script-manager.php#L45 this function in order to enqueu all CSS and JS nedded. Also make sure all js files are loaded in footer.

**Comment by TeoAlex** [comment]
Requires minification of css & js files
