### ISSUE TITLE
Save settings with the right format

### ISSUE THREAD

**Issue by giucu91** [WPChill/modula-lite#868]
`{
    "type": "custom-grid",
    "grid_type": "",
    "grid_row_height": "",
    "grid_justify_last_row": "",
    "grid_image_size": "medium",
    "grid_image_dimensions": "",
    "img_size": "",
    "img_crop": "0",
    "grid_image_crop": "0",
    "gutter": "10",
    "tablet_gutter": "10",
    "mobile_gutter": "10",
    "width": "",
    "height": "",
    "randomFactor": "",
    "shuffle": "0",
    "lightbox": "fancybox",
    "show_navigation": "1",
    "hide_title": "1",
    "titleColor": "",
    "titleFontSize": 0,
    "mobileTitleFontSize": "12",
    "hide_description": "0",
    "captionColor": "#ffffff",
    "captionFontSize": 14,
    "mobileCaptionFontSize": "10",
    "enableSocial": "0",
    "enableTwitter": "0",
    "enableFacebook": "0",
    "enableWhatsapp": "0",
    "enableLinkedin": "0",
    "enablePinterest": "0",
    "enableEmail": "0",
    "emailSubject": "Check out this awesome image !!",
    "emailMessage": "Here is the link to the image : %%image_link%% and this is the link to the gallery : %%gallery_link%%",
    "socialIconColor": "#ffffff",
    "socialIconSize": 16,
    "socialIconPadding": 10,
    "loadedScale": 100,
    "inView": "0",
    "effect": "pufrobo",
    "cursor": "zoom-in",
    "borderSize": 0,
    "borderRadius": 0,
    "borderColor": "#ffffff",
    "shadowSize": 0,
    "shadowColor": "#ffffff",
    "lazy_load": "1",
    "enable_responsive": "0",
    "tablet_columns": "2",
    "mobile_columns": "1",
    "style": "",
    "last_visited_tab": "modula-general",
    "helpergrid": 0,
    "images": [],
    "galleryId": 9,
    "galleryTitle": "",
    "fontSize": 16,
    "imageTitleVisibility": "visible",
    "galleryType": "masonry"
}`

He have number that are strings, we have number that are boolean.

1. We need to ensure that we save the right format.
2. We need to check the type of settings for the REST responses.

**Comment by razvanaldea89** [comment]
@TeoAlex please check all fields and their data type to correspond between saving them, retrieving them and defining them.

**Comment by razvanaldea89** [comment]
Seems like on a talk between @giucu91 and @TeoAlex the settings should remain the same, at least for now. Going to close this.
