### ISSUE TITLE
Aria attributes and accessibility doesn't seem to be implemented correctly

### ISSUE THREAD

**Issue by cristianraiber** [WPChill/modula-lite#884]
More info here: https://wordpress.org/support/topic/aria-attributes-do-not-match-their-roles-5/

**Comment by TeoAlex** [comment]
Could not reproduce the issue
![image](https://github.com/WPChill/modula-lite/assets/19348508/1777cd8a-5dc9-45c6-bd16-d8e001965578)

**Comment by itineris-milos** [comment]
Hi guys, when we can expect the new update for the accessibility issue? We can still replicate
Thanks

**Comment by cristianraiber** [comment]
@itineris-milos - can you please tell me how you replicate the issue? we couldn't replicate it at our ends

**Comment by itineris-milos** [comment]
@cristianraiber See attached screen, you can replicate with the Lightbox option selected.

![image](https://github.com/WPChill/modula-lite/assets/29227000/c6b4e406-1b70-4b46-88e4-4d1ea56bedce)

URL: https://demo.wp-modula.com/modula-gallery/watermark/

Thanks

**Comment by cristianraiber** [comment]
@itineris-milos - fix has been added by @TeoAlex here: https://github.com/WPChill/modula-lite/commit/1c7f729aad8c22535388a0887e50fe4c7bbbafde

It will be available in our next product update.

**Comment by itineris-milos** [comment]
Thanks @cristianraiber for the quick action, appreciate really

**Comment by cristianraiber** [comment]
@itineris-milos 

If you want to apply this fix now you can add the following code at the end of your functions.php file in the active theme's directory.


```
add_filter( 'modula_shortcode_item_data', 'modula_aria_label_fix', 16, 3 );
function modula_aria_label_fix( $item_data, $item, $settings ){
	if( 'fancybox' == $settings['lightbox'] ){
		$item_data['link_attributes']['role'] = 'button';
	}
	return $item_data;
}
```

**Comment by itineris-milos** [comment]
Awesome, I'll give it a go!
