### ISSUE TITLE
Lightbox & links settings - overhaul

### ISSUE THREAD

**Issue by cristianraiber** [WPChill/modula-lite#885]
![CleanShot 2023-12-07 at 12 25 56@2x](https://github.com/WPChill/modula-lite/assets/7841556/4dfd29b4-d5fb-409c-ba28-99f5f096c12b)

**Comment by cristianraiber** [comment]
**For Modula LITE:**
- Attachment page option in the dropdown should be swapped out (replaced) with "External URL". All "attachment page" functionality should be removed as well. Since WP 6.4 attachment pages are disabled, by default: https://make.wordpress.org/core/2023/10/16/changes-to-attachment-pages/

- The URL field, that shows in the lightbox, when editing an image, should only show up IF the user has selected "External URL" in the dropdown field, pictured above.

**Comment by cristianraiber** [comment]
🚨🚨🚨**For Modula PRO**

- No changes will be made; the 'URL' field in the Lightbox supersedes any other options set under Lightbox & Links. The intention is to maintain galleries where certain images can open external URLs, while others will be displayed in a lightbox.

This is intended behaviour and it's a PRO feature.

**Comment by razvanaldea89** [comment]
![image](https://github.com/WPChill/modula-lite/assets/44024114/432b2554-3e15-401c-a6c2-790312af7fb9)
@TeoAlex  this is not done
