### ISSUE TITLE
Update lightbox to Fancybox 5

### ISSUE THREAD

**Issue by TeoAlex** [WPChill/modula-lite#894]

**Comment by giucu91** [comment]
- [ ] In noua implementare de fancybox v5 nu mai folosim jQuery. O sa folosim doar javascript deoarece scopul e ca anul asta frontul de la modula sa fie fara jQuery.

- [ ] https://github.com/WPChill/modula-lite/blob/2.8.0/assets/js/front/fancybox.js#L1-L203 acest cod sa il scoatem din fancybox.js, ori il punem in jquery-modula ori cream modulafancybox.js

- [ ] Partea de share buttons ( https://github.com/WPChill/modula-lite/blob/2.8.0/assets/js/front/fancybox.js#L104 )
	- https://github.com/WPChill/modula-lite/blob/2.8.0/assets/js/front/fancybox.js#L111 il cream in php si il adaugam cu wp add inline script
	- folosim functia asta de templating ca sa nu mai avem replace-urile alea urate din cod ( https://gist.github.com/iiidefix/f61ef86d11b9f17eb3a8 )
	- pentru butonul de share o sa folosim metoda de custom button de la fancybox - https://fancyapps.com/fancybox/plugins/toolbar/#custom-button

**Comment by cristinnaiulia** [comment]
https://github.com/WPChill/modula-video/issues/76

**Comment by cristeacosmin** [comment]
#943
