### ISSUE TITLE
Ajax warning 

### ISSUE THREAD

**Issue by beatricelucaci** [WPChill/modula-lite#908]
**Describe the bug**

When adding a new gallery using a default gallery template I receive an Ajax warning…

Object

component: "Plugin: modula-best-grid-gallery"

file: "wp-content/plugins/modula-best-grid-gallery/includes/class-modula-gutenberg.php"

key: “xxxx (anonymized by me)"

line: 167

message: "Trying to access array offset on value of type bool"

stack: ["Modula_Gutenberg->get_gallery_meta()", "do_action('wp_ajax_modula_get_gallery_meta')"] (2)

type: "warning"

Object Prototype

__defineGetter__(propertyName, getterFunction)

__defineSetter__(propertyName, setterFunction)

__lookupGetter__(propertyName)

__lookupSetter__(propertyName)

constructor: function()

hasOwnProperty(propertyName)

isPrototypeOf(property)

propertyIsEnumerable(propertyName)

toLocaleString()

toString()

valueOf()

https://support.wpchill.com/conversation/10854?folder_id=81

**Comment by TeoAlex** [comment]
Could not replicate this issue on multiple installs. This may have been fixed by fixing other issues.
