### ISSUE TITLE
Custom CSS ">" problem

### ISSUE THREAD

**Issue by razvanaldea89** [WPChill/modula-lite#924]
**Describe the bug**
The Custom CSS tab is not fully functioning. If you enter ">" selector in the editor it will be converted on the front to something else, and the CSS won't work anymore.

**To Reproduce**
1. Go to gallery and add some CSS with ">" in it
2. Check on front if CSS is working

**Expected behavior**
The CSS should be working, this seems an escaping issue.

**Screenshots**

* Which addons do you have installed: 
- [ ] Modula PRO
- [ ] Albums
- [ ] Slider
- [ ] Lightbox Slideshow
- [ ] Password Protect
- [ ] Watermark
- [ ] Deeplink
- [ ] Right-Click Protection
- [ ] Advanced Shortcode
- [ ] SpeedUp
- [ ] Video

* Which browser is affected (or browsers): 
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other 

* Which device is affected (or devices): 
- [ ] Desktop
- [ ] Tablet
- [ ] Mobile
- [ ] Other 

#### Used versions
* WordPress version: 
* Modula Lite version: 
* Modula PRO version: -
* Albums version: -
* Slider version: -
* Lightbox Slideshow version: -
* Password Protect version: -
* Watermark version: -
* Deeplink version: -
* Right-Click Protection version: -
* Advanced Shortcode version: -
* SpeedUp version: -
* Video version: -

**Comment by cristeacosmin** [comment]
@TeoAlex probabil e legat de cum se sanitizeaza acel custom css field, hai sa vedem cum sanitizeaza wordpress pentru functionalitatea de additional css ( de ex. din customizer ) - facem si noi la fel
