### ISSUE TITLE
Change image attribution license selection from radio to select input

### ISSUE THREAD

**Issue by TeoAlex** [WPChill/modula-lite#930]
\

**Comment by TeoAlex** [comment]
https://github.com/TeoAlex/modula-lite/commit/13effec344c823726594f6da3e82f00d8ec9215c

**Comment by cristinnaiulia** [comment]
A fost lansat
![Screenshot 2024-04-24 122906](https://github.com/WPChill/modula-lite/assets/63049546/638499b1-aef8-45eb-83f6-2d95f1d0301a)
