### ISSUE TITLE
Add filters to skip verifying images when displayed in gallery

### ISSUE THREAD

**Issue by TeoAlex** [WPChill/modula-lite#939]
This is necessary so we can add custom templates to be loaded in gallery by different plugins. Now, they are used for Modula Video's https://github.com/WPChill/modula-video/issues/81 issue.

Also modify the add image/upload image buttons to be a dropdown with actions to add additional options

**Comment by cristinnaiulia** [comment]
![Screenshot 2024-05-21 113705](https://github.com/WPChill/modula-lite/assets/63049546/33cfbf82-2fc1-49bb-9fed-2e8bad3a6cd4)
