### ISSUE TITLE
Social links

### ISSUE THREAD

**Issue by razvanaldea89** [WPChill/modula-lite#945]
**Is your feature request related to a problem? Please describe.**
Prepare social links so that we share the page where the gallery resides, but with meta from the image itself ( twitter:card, og:description etc...  ). Also, what we should do is to append the Deeplink parameters, so that when the visitor clicks the shared link, if the website has the Deeplink extension, it will open the image in the lightbox.

**Comment by cristinnaiulia** [comment]
Twitter and pinterest links don't work. I have these errors in console: 

![Screenshot 2024-05-27 112303](https://github.com/WPChill/modula-lite/assets/63049546/a2775495-93c9-4dae-ac41-e47e8c062111)

**Comment by beatricelucaci** [comment]
The deeplink feature works properly on Twitter and there is a preview of the image so it seems to work properly. However, only the title is displayed. The captions seem to be missing
![image](https://github.com/WPChill/modula-lite/assets/84579642/dea95341-0330-4e0e-9008-b8cc94bf9bbc)

**Comment by cristeacosmin** [comment]
Added caption. template is {TITLE} - {CAPTION} [2687289](https://github.com/WPChill/modula-lite/pull/943/commits/2687289b5d8aafd72f4d8e69a86743f4afca1d15)
