### ISSUE TITLE
Social icons

### ISSUE THREAD

**Issue by razvanaldea89** [WPChill/modula-lite#946]
**Is your feature request related to a problem? Please describe.**
Social icons should not be displayed all, by default, a singular share icon should be displayed and clicking that icon will reveal the social icons.

![CleanShot 2024-05-21 at 10 05 40@2x](https://github.com/WPChill/modula-lite/assets/44024114/4b9a0712-800d-4ce7-9551-1fdbf9f59685)

**Comment by TeoAlex** [comment]
https://github.com/TeoAlex/modula-lite/commit/550ef2cbc3eb14c92860f3a1accf2cdf01f8efab

**Comment by cristeacosmin** [comment]
@TeoAlex e pe branchul tau, branchul 2.8.4 sau dev nu are codul acesta . refa comitul sau pr -> merge ca sa pot testa

**Comment by cristeacosmin** [comment]
Social bar improvements

Let's see how people use it and if we need to refactor it
