### ISSUE TITLE
fancybox-image element width and height

### ISSUE THREAD

**Issue by razvanaldea89** [WPChill/modula-lite#955]
**Describe the bug**
Think we should add the following to the element style:

`width: auto; height: auto; max-width: 100%; max-height: 100%`

This way you can add borders to the image without adding unwanted spaces.

**To Reproduce**
1. Go to gallery, open lightbox and add border to image
2. See spaces inside the border

**Comment by cristinnaiulia** [comment]
![Screenshot 2024-06-03 092858](https://github.com/WPChill/modula-lite/assets/63049546/81ff9b3e-a3d3-47d2-9ba0-ec078c715276)
![Screenshot 2024-06-03 092910](https://github.com/WPChill/modula-lite/assets/63049546/a928c16f-58c9-46ee-bdbc-63ac566fb3f8)
