### ISSUE TITLE
Make the "Add New" button a little more beautiful

### ISSUE THREAD

**Issue by razvanaldea89** [WPChill/modula-lite#964]
<img width="313" alt="image" src="https://github.com/WPChill/modula-lite/assets/44024114/01860e1a-c6af-4bc3-9484-209f50724961">

**Comment by cristeacosmin** [comment]
sugestii? foloseste wp core styling care e in aceeasi poveste cu tot pluginul

**Comment by razvanaldea89** [comment]
Feedback de la un client, zicea ca e urat butonul ala acolo. Daca cumva trecem pe Tailwind si cu Modula : https://tailwindui.com/components/application-ui/elements/dropdowns 
Eventual putem lua cate ceva de la felul cum arata la Tailwind daca nu vom face trecerea
