### ISSUE TITLE
Menu problem

### ISSUE THREAD

**Issue by razvanaldea89** [WPChill/modula-lite#974]
**Describe the bug**
When Trio license active and Modula Albums active, the Defaults upsell does not show right.

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://github.com/WPChill/modula-lite/assets/44024114/d3d156db-0299-4c1d-92e5-09a8ff4752c3)

* Which addons do you have installed: 
- [ ] Modula PRO
- [ ] Albums
- [ ] Slider
- [ ] Lightbox Slideshow
- [ ] Password Protect
- [ ] Watermark
- [ ] Deeplink
- [ ] Right-Click Protection
- [ ] Advanced Shortcode
- [ ] SpeedUp
- [ ] Video

* Which browser is affected (or browsers): 
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other 

* Which device is affected (or devices): 
- [ ] Desktop
- [ ] Tablet
- [ ] Mobile
- [ ] Other 

#### Used versions
* WordPress version: 
* Modula Lite version: 
* Modula PRO version: -
* Albums version: -
* Slider version: -
* Lightbox Slideshow version: -
* Password Protect version: -
* Watermark version: -
* Deeplink version: -
* Right-Click Protection version: -
* Advanced Shortcode version: -
* SpeedUp version: -
* Video version: -

**Comment by cristinnaiulia** [comment]
![Screenshot 2024-07-17 092135](https://github.com/user-attachments/assets/99800d41-6cad-4a9a-ae01-a5dce7bc1941)
