### ISSUE TITLE
Filter galleries admin list table by gallery type ( Creative, Custom, Masonry, Slider, Video )

### ISSUE THREAD

**Issue by TeoAlex** [WPChill/modula-lite#980]
![image](https://github.com/WPChill/modula-lite/assets/19348508/c13103d6-7514-414b-8510-7dccab78bafd)

**Comment by cristinnaiulia** [comment]
![Screenshot 2024-08-09 103934](https://github.com/user-attachments/assets/62000613-5f8b-4d48-b192-82f7e0d7806d)
