### ISSUE TITLE
Image attribution license selector improvement

### ISSUE THREAD

**Issue by TeoAlex** [WPChill/modula-lite#986]
Improve visibility of license select. As an ideea we should use the radio-icon select we have for gallery type.
[  ] License Name with link
<image>

**Comment by cristeacosmin** [comment]
e implementat? @TeoAlex

**Comment by cristeacosmin** [comment]
@TeoAlex ping

**Comment by cristinnaiulia** [comment]
When I select an image license, the page goes up.
https://github.com/user-attachments/assets/edade10e-b137-4203-ae4b-1e9c8385a098

**Comment by TeoAlex** [comment]
Could not reproduce the issue.

**Comment by andrei-l-cristea** [comment]
https://github.com/user-attachments/assets/334ac107-a648-4cc5-8ac5-165706177d22

works fine for me

**Comment by TeoAlex** [comment]
Fixed in Image Licensing module
