### ISSUE TITLE
RTL elements orientation 

### ISSUE THREAD

**Issue by beatricelucaci** [WPChill/modula-lite#987]
**Is your feature request related to a problem? Please describe.**
I have a problem with the orientations of the elements in the following image
https://prnt.sc/PndgJZ43wjaS
I need the elements to start from right to left and fill the space from the right because the language of the site is Arabic (RTL)

https://support.wpchill.com/conversation/15794?folder_id=81

**Comment by TeoAlex** [comment]
To change the orientation so the gallery elements start from right to left add this code to the theme functions.php file. This will se the gallery origin to right.

function modula_rtl_gallery() {
    ?>
    <script type="text/javascript">
        jQuery(document).on('modula_api_before_init', function(event, instance) {
            instance.options.originLeft = false;
        });
    </script>
    <?php
}
add_action( 'wp_footer', 'modula_rtl_gallery', 20 );
