### ISSUE TITLE
Lightbox effect on mobile

### ISSUE THREAD

**Issue by andrei-l-cristea** [WPChill/modula-lite#989]
Cand folosesti lightbox pentru imaginile din galerie se intampla ceva ciudat cu overlay-ul.

Pentru testat
1. Pe mobil intra pe : https://support.tamewp.com/a-new-test-page/
2. Dai click pe o imagine sa deschizi lightbox
3. Inchizi lightbox

Ar trebui sa se inchide modalul, iar overlay-ul sa mai ramana foarte putin, dupa care sa se inchida si el. 
![lightbox-desktop-behavior](https://github.com/WPChill/modula-lite/assets/53428716/f993ab8d-56c0-4b40-9930-4e5a63b9cb46)

Pe mobil se inchide lightbox, dupa care apare pentru foarte putin timp overlay-ul si dupa se inchide.

https://github.com/WPChill/modula-lite/assets/53428716/012443d2-65cc-42b0-b56d-0c1821b17725

**Comment by TeoAlex** [comment]
Cannot be tested by itself. Get the commit in PRO from the above mentioned issue.
